-- SQL lessons seed data (100 levels)

INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 1, 'SELECT Basics', 'SQL is used to query databases. SELECT retrieves data. FROM specifies the table. Asterisk (*) selects all columns.', 'SELECT * FROM users;', 'complete_code', 'Write a query that selects all columns from the ''products'' table.', 'SELECT  FROM products;', 'SELECT * FROM products;', 'Use * to select all columns.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 2, 'SELECT Specific Columns', 'Specify column names after SELECT to get only those columns. Separate multiple columns with commas.', 'SELECT name, email FROM users;', 'complete_code', 'Select only the ''name'' and ''price'' columns from the ''products'' table.', 'SELECT  FROM products;', 'SELECT name, price FROM products;', 'List the column names separated by commas.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 3, 'WHERE Clause', 'The WHERE clause filters rows based on conditions. Use =, !=, <, >, <=, >= for comparisons.', 'SELECT * FROM users WHERE age > 18;', 'complete_code', 'Select all columns from ''products'' where price is greater than 100.', 'SELECT * FROM products WHERE price > 100;', 'SELECT * FROM products WHERE price > 100;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 4, 'AND Operator', 'Use AND to combine multiple conditions. Both conditions must be true for the row to be included.', 'SELECT * FROM users WHERE age > 18 AND city = ''London'';', 'complete_code', 'Select products where price > 50 AND category = ''Electronics''.', 'SELECT * FROM products WHERE price > 50 AND category = ''Electronics'';', 'SELECT * FROM products WHERE price > 50 AND category = ''Electronics'';', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 5, 'OR Operator', 'Use OR when at least one condition must be true. OR has lower precedence than AND.', 'SELECT * FROM users WHERE city = ''London'' OR city = ''Paris'';', 'complete_code', 'Select products where category = ''Shoes'' OR category = ''Hats''.', 'SELECT * FROM products WHERE category = ''Shoes'' OR category = ''Hats'';', 'SELECT * FROM products WHERE category = ''Shoes'' OR category = ''Hats'';', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 6, 'NOT Operator', 'NOT negates a condition. Use NOT IN, NOT LIKE, NOT BETWEEN, or NOT before a comparison.', 'SELECT * FROM users WHERE NOT city = ''London'';', 'complete_code', 'Select products where category is NOT ''Electronics''.', 'SELECT * FROM products WHERE NOT category = ''Electronics'';', 'SELECT * FROM products WHERE NOT category = ''Electronics'';', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 7, 'IN Operator', 'IN checks if a value matches any value in a list. It''s cleaner than multiple OR conditions.', 'SELECT * FROM users WHERE city IN (''London'', ''Paris'', ''Berlin'');', 'complete_code', 'Select products where category is ''Food'' or ''Drinks'' using IN.', 'SELECT * FROM products WHERE category IN (''Food'', ''Drinks'');', 'SELECT * FROM products WHERE category IN (''Food'', ''Drinks'');', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 8, 'BETWEEN Operator', 'BETWEEN selects values within a range. The range is inclusive of both endpoints.', 'SELECT * FROM users WHERE age BETWEEN 18 AND 30;', 'complete_code', 'Select products with price between 10 and 50.', 'SELECT * FROM products WHERE price BETWEEN 10 AND 50;', 'SELECT * FROM products WHERE price BETWEEN 10 AND 50;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 9, 'LIKE Operator', 'LIKE searches for patterns. % matches any sequence of characters. _ matches a single character.', 'SELECT * FROM users WHERE name LIKE ''J%'';', 'complete_code', 'Select products where name starts with ''A''.', 'SELECT * FROM products WHERE name LIKE ''A%'';', 'SELECT * FROM products WHERE name LIKE ''A%'';', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 10, 'ORDER BY', 'ORDER BY sorts results. ASC for ascending (default), DESC for descending.', 'SELECT * FROM users ORDER BY age DESC;', 'complete_code', 'Select all products ordered by price from highest to lowest.', 'SELECT * FROM products ORDER BY price DESC;', 'SELECT * FROM products ORDER BY price DESC;', 'Use ORDER BY price DESC.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 11, 'LIMIT', 'LIMIT restricts the number of rows returned. Use LIMIT with OFFSET to skip rows.', 'SELECT * FROM users LIMIT 5;', 'complete_code', 'Select the first 10 products.', 'SELECT * FROM products LIMIT 10;', 'SELECT * FROM products LIMIT 10;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 12, 'DISTINCT', 'DISTINCT removes duplicate values from the result. It applies to the selected columns.', 'SELECT DISTINCT city FROM users;', 'complete_code', 'Select distinct categories from the products table.', 'SELECT DISTINCT category FROM products;', 'SELECT DISTINCT category FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 13, 'COUNT', 'COUNT() returns the number of rows. COUNT(*) counts all rows. COUNT(column) counts non-null values.', 'SELECT COUNT(*) FROM users;', 'complete_code', 'Count how many products are in the products table.', 'SELECT COUNT(*) FROM products;', 'SELECT COUNT(*) FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 14, 'SUM', 'SUM() adds up all values in a numeric column. NULL values are ignored.', 'SELECT SUM(price) FROM products;', 'complete_code', 'Calculate the total price of all products.', 'SELECT SUM(price) FROM products;', 'SELECT SUM(price) FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 15, 'AVG', 'AVG() calculates the average of a numeric column. NULL values are ignored.', 'SELECT AVG(price) FROM products;', 'complete_code', 'Calculate the average price of products.', 'SELECT AVG(price) FROM products;', 'SELECT AVG(price) FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 16, 'MIN and MAX', 'MIN() returns the smallest value. MAX() returns the largest value. They work on numeric and text columns.', 'SELECT MIN(price), MAX(price) FROM products;', 'complete_code', 'Find the minimum and maximum price from products.', 'SELECT MIN(price), MAX(price) FROM products;', 'SELECT MIN(price), MAX(price) FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 17, 'GROUP BY', 'GROUP BY groups rows that have the same values. Used with aggregate functions like COUNT, SUM, AVG.', 'SELECT category, COUNT(*) FROM products GROUP BY category;', 'complete_code', 'Count the number of products in each category.', 'SELECT category, COUNT(*) FROM products GROUP BY category;', 'SELECT category, COUNT(*) FROM products GROUP BY category;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 18, 'HAVING', 'HAVING filters groups created by GROUP BY. WHERE filters rows before grouping, HAVING filters after.', 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 5;', 'complete_code', 'Show categories that have more than 10 products.', 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 10;', 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 10;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 19, 'AS Alias', 'AS gives a column or table a temporary name. Aliases make queries more readable.', 'SELECT COUNT(*) AS total_users FROM users;', 'complete_code', 'Use an alias to rename COUNT(*) as ''total_products''.', 'SELECT COUNT(*) AS total_products FROM products;', 'SELECT COUNT(*) AS total_products FROM products;', 'The answer is already in the template.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 20, 'NULL Values', 'NULL represents missing data. Use IS NULL or IS NOT NULL to check for NULL. Cannot use = NULL.', 'SELECT * FROM users WHERE email IS NULL;', 'complete_code', 'Select products where the description is not NULL.', 'SELECT * FROM products WHERE description IS NOT NULL;', 'SELECT * FROM products WHERE description IS NOT NULL;', 'Use IS NOT NULL.', 50, 'easy', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 21, 'UPDATE', 'UPDATE modifies existing rows. Always use WHERE to avoid updating all rows. SET specifies new values.', 'UPDATE users SET age = 30 WHERE id = 1;', 'complete_code', 'Update the price of product with id 1 to 25.99.', 'UPDATE products SET price = 25.99 WHERE id = 1;', 'UPDATE products SET price = 25.99 WHERE id = 1;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 22, 'DELETE', 'DELETE removes rows from a table. Always use WHERE. Without WHERE, all rows are deleted.', 'DELETE FROM users WHERE id = 1;', 'complete_code', 'Delete the product with id 5.', 'DELETE FROM products WHERE id = 5;', 'DELETE FROM products WHERE id = 5;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 23, 'INSERT INTO', 'INSERT adds new rows. Specify columns and values. If no columns listed, values for all columns are needed.', 'INSERT INTO users (name, email) VALUES (''John'', ''john@test.com'');', 'complete_code', 'Insert a new product with name ''Chair'' and price 49.99.', 'INSERT INTO products (name, price) VALUES (''Chair'', 49.99);', 'INSERT INTO products (name, price) VALUES (''Chair'', 49.99);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 24, 'CREATE TABLE', 'CREATE TABLE defines a new table. Specify column names and data types: INT, VARCHAR(n), DECIMAL, DATE, BOOLEAN.', 'CREATE TABLE users (id INT, name VARCHAR(100), email VARCHAR(255));', 'complete_code', 'Create a table ''orders'' with columns id INT and total DECIMAL(10,2).', 'CREATE TABLE orders (id INT, total DECIMAL(10,2));', 'CREATE TABLE orders (id INT, total DECIMAL(10,2));', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 25, 'ALTER TABLE', 'ALTER TABLE modifies an existing table. Add, drop, or modify columns.', 'ALTER TABLE users ADD COLUMN phone VARCHAR(20);', 'complete_code', 'Add a column ''discount'' of type DECIMAL(5,2) to the products table.', 'ALTER TABLE products ADD COLUMN discount DECIMAL(5,2);', 'ALTER TABLE products ADD COLUMN discount DECIMAL(5,2);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 26, 'DROP TABLE', 'DROP TABLE permanently removes a table and all its data. This action cannot be undone.', 'DROP TABLE IF EXISTS temp_data;', 'true_false', 'DROP TABLE can be rolled back with ROLLBACK.', '', 'false', 'DROP TABLE is a DDL statement and cannot be rolled back.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 27, 'PRIMARY KEY', 'A PRIMARY KEY uniquely identifies each row. It cannot be NULL. A table can have only one primary key.', 'CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(100));', 'complete_code', 'Create a table ''products'' with id INT as PRIMARY KEY.', 'CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(100));', 'CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(100));', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 28, 'FOREIGN KEY', 'A FOREIGN KEY links two tables. It references a PRIMARY KEY in another table. Enforces referential integrity.', 'CREATE TABLE orders (id INT PRIMARY KEY, user_id INT REFERENCES users(id));', 'complete_code', 'Add a FOREIGN KEY on product_id referencing products(id).', 'CREATE TABLE order_items (id INT PRIMARY KEY, product_id INT REFERENCES products(id));', 'CREATE TABLE order_items (id INT PRIMARY KEY, product_id INT REFERENCES products(id));', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 29, 'UNIQUE Constraint', 'UNIQUE ensures all values in a column are different. A table can have multiple UNIQUE constraints.', 'CREATE TABLE users (id INT PRIMARY KEY, email VARCHAR(255) UNIQUE);', 'true_false', 'A table can have multiple UNIQUE constraints.', '', 'true', 'Unlike PRIMARY KEY, you can have multiple UNIQUE columns.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 30, 'NOT NULL', 'NOT NULL ensures a column cannot have a NULL value. It''s a constraint at the column level.', 'CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL);', 'complete_code', 'Create a table with name column set to NOT NULL.', 'CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL);', 'CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 31, 'DEFAULT Value', 'DEFAULT sets a default value for a column when no value is provided in INSERT.', 'CREATE TABLE users (id INT, status VARCHAR(20) DEFAULT ''active'');', 'complete_code', 'Set a default value of 0 for the ''stock'' column.', 'CREATE TABLE products (id INT, stock INT DEFAULT 0);', 'CREATE TABLE products (id INT, stock INT DEFAULT 0);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 32, 'AUTO INCREMENT', 'AUTO_INCREMENT (MySQL) or GENERATED AS IDENTITY (PostgreSQL) automatically generates unique numbers.', 'CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));', 'true_false', 'AUTO_INCREMENT guarantees that values are always consecutive.', '', 'false', 'Auto-increment values can have gaps due to rollbacks or deletions.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 33, 'INNER JOIN', 'INNER JOIN returns rows that have matching values in both tables. Only matching rows are included.', 'SELECT users.name, orders.total FROM users INNER JOIN orders ON users.id = orders.user_id;', 'complete_code', 'Join products with order_items on product_id.', 'SELECT products.name, order_items.quantity FROM products INNER JOIN order_items ON products.id = order_items.product_id;', 'SELECT products.name, order_items.quantity FROM products INNER JOIN order_items ON products.id = order_items.product_id;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 34, 'LEFT JOIN', 'LEFT JOIN returns all rows from the left table, and matching rows from the right table. Non-matching right rows show NULL.', 'SELECT users.name, orders.total FROM users LEFT JOIN orders ON users.id = orders.user_id;', 'complete_code', 'Use LEFT JOIN to get all products with their order quantities.', 'SELECT products.name, order_items.quantity FROM products LEFT JOIN order_items ON products.id = order_items.product_id;', 'SELECT products.name, order_items.quantity FROM products LEFT JOIN order_items ON products.id = order_items.product_id;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 35, 'RIGHT JOIN', 'RIGHT JOIN returns all rows from the right table, and matching rows from the left table.', 'SELECT users.name, orders.total FROM users RIGHT JOIN orders ON users.id = orders.user_id;', 'predict_output', 'What does RIGHT JOIN return for non-matching left table rows?', '', 'NULL', 'Non-matching rows from the left table show NULL.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 36, 'FULL JOIN', 'FULL JOIN (or FULL OUTER JOIN) returns all rows from both tables. NULLs appear where there is no match.', 'SELECT users.name, orders.total FROM users FULL JOIN orders ON users.id = orders.user_id;', 'true_false', 'FULL JOIN is supported in all SQL databases.', '', 'false', 'MySQL does not support FULL JOIN directly.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 37, 'CROSS JOIN', 'CROSS JOIN returns the Cartesian product of both tables. Each row from table A is paired with each row from table B.', 'SELECT * FROM products CROSS JOIN categories;', 'predict_output', 'If table A has 3 rows and table B has 4 rows, how many rows does CROSS JOIN return?', '', '12', 'Multiply the row counts of both tables.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 38, 'SELF JOIN', 'A SELF JOIN joins a table with itself. Use table aliases to distinguish the two instances.', 'SELECT e1.name AS employee, e2.name AS manager FROM employees e1 INNER JOIN employees e2 ON e1.manager_id = e2.id;', 'complete_code', 'Self join the employees table to find employee names with their manager names.', 'SELECT e1.name AS employee, e2.name AS manager FROM employees e1 INNER JOIN employees e2 ON e1.manager_id = e2.id;', 'SELECT e1.name AS employee, e2.name AS manager FROM employees e1 INNER JOIN employees e2 ON e1.manager_id = e2.id;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 39, 'Subquery', 'A subquery is a query inside another query. It can be used in SELECT, FROM, or WHERE clauses.', 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);', 'complete_code', 'Select products with price above the average price using a subquery.', 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);', 'SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 40, 'EXISTS', 'EXISTS checks if a subquery returns any rows. It returns true if the subquery has at least one row.', 'SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);', 'complete_code', 'Select products that exist in order_items using EXISTS.', 'SELECT * FROM products WHERE EXISTS (SELECT 1 FROM order_items WHERE order_items.product_id = products.id);', 'SELECT * FROM products WHERE EXISTS (SELECT 1 FROM order_items WHERE order_items.product_id = products.id);', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 41, 'ANY and ALL', 'ANY compares a value to any value in a subquery. ALL compares to all values. Use with =, <, >, etc.', 'SELECT * FROM products WHERE price > ANY (SELECT price FROM products WHERE category = ''Premium'');', 'predict_output', 'What does > ALL return if the subquery returns (10, 20, 30)?', '', 'greater than 30', 'ALL means greater than every value in the list.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 42, 'UNION', 'UNION combines results from multiple SELECT queries. Duplicate rows are removed. UNION ALL keeps duplicates.', 'SELECT name FROM customers UNION SELECT name FROM suppliers;', 'complete_code', 'Combine product names from two tables: current_products and discontinued_products.', 'SELECT name FROM current_products UNION SELECT name FROM discontinued_products;', 'SELECT name FROM current_products UNION SELECT name FROM discontinued_products;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 43, 'INTERSECT', 'INTERSECT returns rows that are common to both SELECT queries. Both queries must have the same number of columns.', 'SELECT name FROM customers INTERSECT SELECT name FROM suppliers;', 'predict_output', 'What does INTERSECT return if one query has ''A'',''B'' and the other has ''B'',''C''?', '', 'B', 'INTERSECT returns only common values.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 44, 'EXCEPT', 'EXCEPT (or MINUS) returns rows from the first query that are not in the second query.', 'SELECT name FROM customers EXCEPT SELECT name FROM suppliers;', 'predict_output', 'What does EXCEPT return if first query has ''A'',''B'' and second has ''B'',''C''?', '', 'A', 'EXCEPT returns rows in the first set but not the second.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 45, 'CASE WHEN', 'CASE WHEN is like an if-else in SQL. It evaluates conditions and returns a value for the first matching condition.', 'SELECT name, CASE WHEN age >= 18 THEN ''Adult'' ELSE ''Minor'' END AS status FROM users;', 'complete_code', 'Create a CASE that labels products as ''Cheap'' if price < 20, else ''Expensive''.', 'SELECT name, CASE WHEN price < 20 THEN ''Cheap'' ELSE ''Expensive'' END AS label FROM products;', 'SELECT name, CASE WHEN price < 20 THEN ''Cheap'' ELSE ''Expensive'' END AS label FROM products;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 46, 'COALESCE', 'COALESCE returns the first non-NULL value from a list of expressions. Useful for providing default values.', 'SELECT name, COALESCE(phone, email, ''No contact'') FROM users;', 'complete_code', 'Use COALESCE to show ''No description'' when description is NULL.', 'SELECT name, COALESCE(description, ''No description'') FROM products;', 'SELECT name, COALESCE(description, ''No description'') FROM products;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 47, 'NULLIF', 'NULLIF returns NULL if two expressions are equal, otherwise returns the first expression.', 'SELECT NULLIF(column1, column2) FROM table;', 'predict_output', 'What does NULLIF(5, 5) return?', '', 'NULL', 'NULLIF returns NULL when the two values are equal.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 48, 'String Functions', 'SQL string functions: UPPER(), LOWER(), LENGTH(), TRIM(), SUBSTRING(), CONCAT(), REPLACE().', 'SELECT UPPER(name), LENGTH(name), CONCAT(first_name, '' '', last_name) FROM users;', 'complete_code', 'Use UPPER to convert the product name to uppercase.', 'SELECT UPPER(name) FROM products;', 'SELECT UPPER(name) FROM products;', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 49, 'Date Functions', 'SQL date functions: NOW(), CURDATE(), DATE(), YEAR(), MONTH(), DAY(), DATE_ADD(), DATEDIFF().', 'SELECT NOW(), CURDATE(), YEAR(order_date) FROM orders;', 'complete_code', 'Select the current date using CURDATE().', 'SELECT CURDATE();', 'SELECT CURDATE();', 'The answer is already in the template.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 50, 'Aggregate Functions', 'Aggregate functions: COUNT, SUM, AVG, MIN, MAX, GROUP_CONCAT. They summarize multiple rows into one.', 'SELECT COUNT(*), SUM(price), AVG(price), MIN(price), MAX(price) FROM products;', 'multiple_choice', 'Which aggregate function returns the number of rows?', 'SUM()
COUNT()
AVG()
MAX()', 'COUNT()', 'COUNT counts the number of rows.', 75, 'medium', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 51, 'GROUP_CONCAT', 'GROUP_CONCAT concatenates values from multiple rows into a single string. Use with GROUP BY.', 'SELECT category, GROUP_CONCAT(name) FROM products GROUP BY category;', 'complete_code', 'Use GROUP_CONCAT to list all product names in each category.', 'SELECT category, GROUP_CONCAT(name) FROM products GROUP BY category;', 'SELECT category, GROUP_CONCAT(name) FROM products GROUP BY category;', 'The answer is already in the template.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 52, 'HAVING vs WHERE', 'WHERE filters rows before grouping. HAVING filters groups after aggregation. HAVING can use aggregate functions.', 'SELECT category, COUNT(*) FROM products WHERE price > 10 GROUP BY category HAVING COUNT(*) > 3;', 'true_false', 'HAVING can be used without GROUP BY.', '', 'true', 'HAVING works without GROUP BY, but it''s uncommon.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 53, 'Nested Subqueries', 'Subqueries can be nested inside other subqueries. Deep nesting can hurt performance.', 'SELECT * FROM products WHERE category_id IN (SELECT id FROM categories WHERE name IN (SELECT name FROM featured_categories));', 'predict_output', 'Can a subquery be used in the SELECT clause?', '', 'yes', 'Subqueries can appear in SELECT, FROM, and WHERE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 54, 'Correlated Subquery', 'A correlated subquery references columns from the outer query. It runs once for each row in the outer query.', 'SELECT p.name, (SELECT COUNT(*) FROM order_items oi WHERE oi.product_id = p.id) AS order_count FROM products p;', 'complete_code', 'Write a correlated subquery to count orders for each product.', 'SELECT p.name, (SELECT COUNT(*) FROM order_items oi WHERE oi.product_id = p.id) AS order_count FROM products p;', 'SELECT p.name, (SELECT COUNT(*) FROM order_items oi WHERE oi.product_id = p.id) AS order_count FROM products p;', 'The answer is already in the template.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 55, 'Indexes', 'Indexes speed up queries. CREATE INDEX creates an index. Use on columns used in WHERE and JOIN.', 'CREATE INDEX idx_users_email ON users(email);', 'complete_code', 'Create an index on the products(name) column.', 'CREATE INDEX idx_products_name ON products(name);', 'CREATE INDEX idx_products_name ON products(name);', 'The answer is already in the template.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 56, 'Views', 'A view is a saved query that acts like a virtual table. CREATE VIEW name AS query.', 'CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;', 'complete_code', 'Create a view named ''expensive_products'' showing products with price > 100.', 'CREATE VIEW expensive_products AS SELECT * FROM products WHERE price > 100;', 'CREATE VIEW expensive_products AS SELECT * FROM products WHERE price > 100;', 'The answer is already in the template.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 57, 'Transactions', 'Transactions group multiple operations. BEGIN, COMMIT, ROLLBACK. All or nothing execution.', 'BEGIN;
UPDATE accounts SET balance = balance - 100 WHERE id = 1;
UPDATE accounts SET balance = balance + 100 WHERE id = 2;
COMMIT;', 'true_false', 'ROLLBACK undoes all changes made in the current transaction.', '', 'true', 'ROLLBACK reverts the transaction to its beginning.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 58, 'ACID Properties', 'ACID: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent transactions), Durability (persisted).', 'ACID properties ensure reliable database transactions.', 'multiple_choice', 'Which ACID property ensures transactions are all-or-nothing?', 'Atomicity
Consistency
Isolation
Durability', 'Atomicity', 'Atomicity means the transaction completes fully or not at all.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 59, 'Stored Procedures', 'A stored procedure is a saved block of SQL code that can be called repeatedly. Use CREATE PROCEDURE.', 'CREATE PROCEDURE GetUsers() BEGIN SELECT * FROM users; END;', 'true_false', 'Stored procedures can accept parameters.', '', 'true', 'Procedures can have IN, OUT, and INOUT parameters.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 60, 'Triggers', 'A trigger runs automatically before or after an INSERT, UPDATE, or DELETE event.', 'CREATE TRIGGER update_timestamp BEFORE UPDATE ON users FOR EACH ROW SET NEW.updated_at = NOW();', 'true_false', 'Triggers can be fired before or after a DML operation.', '', 'true', 'Triggers use BEFORE or AFTER timing.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 61, 'SQL Advanced 1', 'This level covers Window Functions in SQL.', '-- Example of Window Functions
SELECT * FROM table;', 'true_false', 'Answer the question about Window Functions.', '-- Window Functions
SELECT * FROM table;', '-- Window Functions
SELECT * FROM table;', 'Review the documentation for Window Functions.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 62, 'SQL Advanced 2', 'This level covers ROW_NUMBER in SQL.', '-- Example of ROW_NUMBER
SELECT * FROM table;', 'predict_output', 'Answer the question about ROW_NUMBER.', '-- ROW_NUMBER
SELECT * FROM table;', '-- ROW_NUMBER
SELECT * FROM table;', 'Review the documentation for ROW_NUMBER.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 63, 'SQL Advanced 3', 'This level covers RANK in SQL.', '-- Example of RANK
SELECT * FROM table;', 'complete_code', 'Answer the question about RANK.', '-- RANK
SELECT * FROM table;', '-- RANK
SELECT * FROM table;', 'Review the documentation for RANK.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 64, 'SQL Advanced 4', 'This level covers DENSE_RANK in SQL.', '-- Example of DENSE_RANK
SELECT * FROM table;', 'true_false', 'Answer the question about DENSE_RANK.', '-- DENSE_RANK
SELECT * FROM table;', '-- DENSE_RANK
SELECT * FROM table;', 'Review the documentation for DENSE_RANK.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 65, 'SQL Advanced 5', 'This level covers NTILE in SQL.', '-- Example of NTILE
SELECT * FROM table;', 'predict_output', 'Answer the question about NTILE.', '-- NTILE
SELECT * FROM table;', '-- NTILE
SELECT * FROM table;', 'Review the documentation for NTILE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 66, 'SQL Advanced 6', 'This level covers LAG and LEAD in SQL.', '-- Example of LAG and LEAD
SELECT * FROM table;', 'complete_code', 'Answer the question about LAG and LEAD.', '-- LAG and LEAD
SELECT * FROM table;', '-- LAG and LEAD
SELECT * FROM table;', 'Review the documentation for LAG and LEAD.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 67, 'SQL Advanced 7', 'This level covers FIRST_VALUE in SQL.', '-- Example of FIRST_VALUE
SELECT * FROM table;', 'true_false', 'Answer the question about FIRST_VALUE.', '-- FIRST_VALUE
SELECT * FROM table;', '-- FIRST_VALUE
SELECT * FROM table;', 'Review the documentation for FIRST_VALUE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 68, 'SQL Advanced 8', 'This level covers LAST_VALUE in SQL.', '-- Example of LAST_VALUE
SELECT * FROM table;', 'predict_output', 'Answer the question about LAST_VALUE.', '-- LAST_VALUE
SELECT * FROM table;', '-- LAST_VALUE
SELECT * FROM table;', 'Review the documentation for LAST_VALUE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 69, 'SQL Advanced 9', 'This level covers CUME_DIST in SQL.', '-- Example of CUME_DIST
SELECT * FROM table;', 'complete_code', 'Answer the question about CUME_DIST.', '-- CUME_DIST
SELECT * FROM table;', '-- CUME_DIST
SELECT * FROM table;', 'Review the documentation for CUME_DIST.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 70, 'SQL Advanced 10', 'This level covers PERCENT_RANK in SQL.', '-- Example of PERCENT_RANK
SELECT * FROM table;', 'true_false', 'Answer the question about PERCENT_RANK.', '-- PERCENT_RANK
SELECT * FROM table;', '-- PERCENT_RANK
SELECT * FROM table;', 'Review the documentation for PERCENT_RANK.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 71, 'SQL Advanced 11', 'This level covers ROLLUP in SQL.', '-- Example of ROLLUP
SELECT * FROM table;', 'predict_output', 'Answer the question about ROLLUP.', '-- ROLLUP
SELECT * FROM table;', '-- ROLLUP
SELECT * FROM table;', 'Review the documentation for ROLLUP.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 72, 'SQL Advanced 12', 'This level covers CUBE in SQL.', '-- Example of CUBE
SELECT * FROM table;', 'complete_code', 'Answer the question about CUBE.', '-- CUBE
SELECT * FROM table;', '-- CUBE
SELECT * FROM table;', 'Review the documentation for CUBE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 73, 'SQL Advanced 13', 'This level covers GROUPING SETS in SQL.', '-- Example of GROUPING SETS
SELECT * FROM table;', 'true_false', 'Answer the question about GROUPING SETS.', '-- GROUPING SETS
SELECT * FROM table;', '-- GROUPING SETS
SELECT * FROM table;', 'Review the documentation for GROUPING SETS.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 74, 'SQL Advanced 14', 'This level covers PIVOT in SQL.', '-- Example of PIVOT
SELECT * FROM table;', 'predict_output', 'Answer the question about PIVOT.', '-- PIVOT
SELECT * FROM table;', '-- PIVOT
SELECT * FROM table;', 'Review the documentation for PIVOT.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 75, 'SQL Advanced 15', 'This level covers UNPIVOT in SQL.', '-- Example of UNPIVOT
SELECT * FROM table;', 'complete_code', 'Answer the question about UNPIVOT.', '-- UNPIVOT
SELECT * FROM table;', '-- UNPIVOT
SELECT * FROM table;', 'Review the documentation for UNPIVOT.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 76, 'SQL Advanced 16', 'This level covers Common Table Expressions in SQL.', '-- Example of Common Table Expressions
SELECT * FROM table;', 'true_false', 'Answer the question about Common Table Expressions.', '-- Common Table Expressions
SELECT * FROM table;', '-- Common Table Expressions
SELECT * FROM table;', 'Review the documentation for Common Table Expressions.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 77, 'SQL Advanced 17', 'This level covers Recursive CTE in SQL.', '-- Example of Recursive CTE
SELECT * FROM table;', 'predict_output', 'Answer the question about Recursive CTE.', '-- Recursive CTE
SELECT * FROM table;', '-- Recursive CTE
SELECT * FROM table;', 'Review the documentation for Recursive CTE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 78, 'SQL Advanced 18', 'This level covers MERGE in SQL.', '-- Example of MERGE
SELECT * FROM table;', 'complete_code', 'Answer the question about MERGE.', '-- MERGE
SELECT * FROM table;', '-- MERGE
SELECT * FROM table;', 'Review the documentation for MERGE.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 79, 'SQL Advanced 19', 'This level covers Bulk Insert in SQL.', '-- Example of Bulk Insert
SELECT * FROM table;', 'true_false', 'Answer the question about Bulk Insert.', '-- Bulk Insert
SELECT * FROM table;', '-- Bulk Insert
SELECT * FROM table;', 'Review the documentation for Bulk Insert.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 80, 'SQL Advanced 20', 'This level covers Table Variables in SQL.', '-- Example of Table Variables
SELECT * FROM table;', 'predict_output', 'Answer the question about Table Variables.', '-- Table Variables
SELECT * FROM table;', '-- Table Variables
SELECT * FROM table;', 'Review the documentation for Table Variables.', 100, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 81, 'SQL Mastery 1', 'Mastering Database Normalization distinguishes expert SQL developers.', '-- Advanced: Database Normalization
SELECT 1;', 'true_false', 'Answer the question about Database Normalization.', '-- Database Normalization
SELECT 1;', '-- Database Normalization
SELECT 1;', 'Review the documentation for Database Normalization.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 82, 'SQL Mastery 2', 'Mastering 1NF distinguishes expert SQL developers.', '-- Advanced: 1NF
SELECT 1;', 'complete_code', 'Answer the question about 1NF.', '-- 1NF
SELECT 1;', '-- 1NF
SELECT 1;', 'Review the documentation for 1NF.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 83, 'SQL Mastery 3', 'Mastering 2NF distinguishes expert SQL developers.', '-- Advanced: 2NF
SELECT 1;', 'true_false', 'Answer the question about 2NF.', '-- 2NF
SELECT 1;', '-- 2NF
SELECT 1;', 'Review the documentation for 2NF.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 84, 'SQL Mastery 4', 'Mastering 3NF distinguishes expert SQL developers.', '-- Advanced: 3NF
SELECT 1;', 'complete_code', 'Answer the question about 3NF.', '-- 3NF
SELECT 1;', '-- 3NF
SELECT 1;', 'Review the documentation for 3NF.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 85, 'SQL Mastery 5', 'Mastering BCNF distinguishes expert SQL developers.', '-- Advanced: BCNF
SELECT 1;', 'true_false', 'Answer the question about BCNF.', '-- BCNF
SELECT 1;', '-- BCNF
SELECT 1;', 'Review the documentation for BCNF.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 86, 'SQL Mastery 6', 'Mastering Denormalization distinguishes expert SQL developers.', '-- Advanced: Denormalization
SELECT 1;', 'complete_code', 'Answer the question about Denormalization.', '-- Denormalization
SELECT 1;', '-- Denormalization
SELECT 1;', 'Review the documentation for Denormalization.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 87, 'SQL Mastery 7', 'Mastering ER Diagrams distinguishes expert SQL developers.', '-- Advanced: ER Diagrams
SELECT 1;', 'true_false', 'Answer the question about ER Diagrams.', '-- ER Diagrams
SELECT 1;', '-- ER Diagrams
SELECT 1;', 'Review the documentation for ER Diagrams.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 88, 'SQL Mastery 8', 'Mastering Cardinality distinguishes expert SQL developers.', '-- Advanced: Cardinality
SELECT 1;', 'complete_code', 'Answer the question about Cardinality.', '-- Cardinality
SELECT 1;', '-- Cardinality
SELECT 1;', 'Review the documentation for Cardinality.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 89, 'SQL Mastery 9', 'Mastering Index Types distinguishes expert SQL developers.', '-- Advanced: Index Types
SELECT 1;', 'true_false', 'Answer the question about Index Types.', '-- Index Types
SELECT 1;', '-- Index Types
SELECT 1;', 'Review the documentation for Index Types.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 90, 'SQL Mastery 10', 'Mastering Query Plan distinguishes expert SQL developers.', '-- Advanced: Query Plan
SELECT 1;', 'complete_code', 'Answer the question about Query Plan.', '-- Query Plan
SELECT 1;', '-- Query Plan
SELECT 1;', 'Review the documentation for Query Plan.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 91, 'SQL Mastery 11', 'Mastering Query Optimization distinguishes expert SQL developers.', '-- Advanced: Query Optimization
SELECT 1;', 'true_false', 'Answer the question about Query Optimization.', '-- Query Optimization
SELECT 1;', '-- Query Optimization
SELECT 1;', 'Review the documentation for Query Optimization.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 92, 'SQL Mastery 12', 'Mastering Execution Plan distinguishes expert SQL developers.', '-- Advanced: Execution Plan
SELECT 1;', 'complete_code', 'Answer the question about Execution Plan.', '-- Execution Plan
SELECT 1;', '-- Execution Plan
SELECT 1;', 'Review the documentation for Execution Plan.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 93, 'SQL Mastery 13', 'Mastering Deadlock distinguishes expert SQL developers.', '-- Advanced: Deadlock
SELECT 1;', 'true_false', 'Answer the question about Deadlock.', '-- Deadlock
SELECT 1;', '-- Deadlock
SELECT 1;', 'Review the documentation for Deadlock.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 94, 'SQL Mastery 14', 'Mastering Isolation Levels distinguishes expert SQL developers.', '-- Advanced: Isolation Levels
SELECT 1;', 'complete_code', 'Answer the question about Isolation Levels.', '-- Isolation Levels
SELECT 1;', '-- Isolation Levels
SELECT 1;', 'Review the documentation for Isolation Levels.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 95, 'SQL Mastery 15', 'Mastering Read Committed distinguishes expert SQL developers.', '-- Advanced: Read Committed
SELECT 1;', 'true_false', 'Answer the question about Read Committed.', '-- Read Committed
SELECT 1;', '-- Read Committed
SELECT 1;', 'Review the documentation for Read Committed.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 96, 'SQL Mastery 16', 'Mastering Repeatable Read distinguishes expert SQL developers.', '-- Advanced: Repeatable Read
SELECT 1;', 'complete_code', 'Answer the question about Repeatable Read.', '-- Repeatable Read
SELECT 1;', '-- Repeatable Read
SELECT 1;', 'Review the documentation for Repeatable Read.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 97, 'SQL Mastery 17', 'Mastering Serializable distinguishes expert SQL developers.', '-- Advanced: Serializable
SELECT 1;', 'true_false', 'Answer the question about Serializable.', '-- Serializable
SELECT 1;', '-- Serializable
SELECT 1;', 'Review the documentation for Serializable.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 98, 'SQL Mastery 18', 'Mastering Snapshot Isolation distinguishes expert SQL developers.', '-- Advanced: Snapshot Isolation
SELECT 1;', 'complete_code', 'Answer the question about Snapshot Isolation.', '-- Snapshot Isolation
SELECT 1;', '-- Snapshot Isolation
SELECT 1;', 'Review the documentation for Snapshot Isolation.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 99, 'SQL Mastery 19', 'Mastering Sharding distinguishes expert SQL developers.', '-- Advanced: Sharding
SELECT 1;', 'true_false', 'Answer the question about Sharding.', '-- Sharding
SELECT 1;', '-- Sharding
SELECT 1;', 'Review the documentation for Sharding.', 150, 'hard', 1);
INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('sql', 100, 'SQL Mastery 20', 'Mastering Partitioning distinguishes expert SQL developers.', '-- Advanced: Partitioning
SELECT 1;', 'complete_code', 'Answer the question about Partitioning.', '-- Partitioning
SELECT 1;', '-- Partitioning
SELECT 1;', 'Review the documentation for Partitioning.', 150, 'hard', 1);