#!/usr/bin/env python3

LESSON_TEMPLATES = []

for i in range(1, 101):
    level = i
    if level <= 20:
        difficulty = "easy"
        xp = 50
    elif level <= 50:
        difficulty = "medium"
        xp = 75
    elif level <= 80:
        difficulty = "hard"
        xp = 100
    else:
        difficulty = "hard"
        xp = 150

    if level == 1:
        title = "Hello World"
        theory = "JavaScript is a programming language for the web. Use console.log() to print output to the browser console."
        code = "console.log('Hello, World!');"
        challenge_type = "complete_code"
        challenge_desc = "Write a console.log statement that prints 'Hello, World!'."
        template = "console.log();"
        answer = "console.log('Hello, World!');"
        hint = "Put the string 'Hello, World!' inside the parentheses."
    elif level == 2:
        title = "Variables with let"
        theory = "The let keyword declares a variable. Use = to assign a value. Variable names are case-sensitive."
        code = "let name = 'Alice';\nconsole.log(name);"
        challenge_type = "complete_code"
        challenge_desc = "Declare a variable named 'message' with the value 'Hello'."
        template = "console.log(message);"
        answer = "let message = 'Hello';\nconsole.log(message);"
        hint = "Use let message = 'Hello'; before the console.log."
    elif level == 3:
        title = "Constants with const"
        theory = "The const keyword declares a constant that cannot be reassigned. Use it for values that should not change."
        code = "const PI = 3.14;\nconsole.log(PI);"
        challenge_type = "complete_code"
        challenge_desc = "Declare a constant named 'greeting' with value 'Hi' and log it."
        template = "console.log(greeting);"
        answer = "const greeting = 'Hi';\nconsole.log(greeting);"
        hint = "Use const greeting = 'Hi'; before the console.log."
    elif level == 4:
        title = "Data Types"
        theory = "JavaScript has types: string, number, boolean, null, undefined, object. Use typeof to check type."
        code = "let name = 'John';\nlet age = 25;\nlet isStudent = true;\nconsole.log(typeof name, typeof age, typeof isStudent);"
        challenge_type = "predict_output"
        challenge_desc = "What is the typeof 'Hello'?"
        template = ""
        answer = "string"
        hint = "The typeof operator returns the type as a string."
    elif level == 5:
        title = "Numbers and Arithmetic"
        theory = "JavaScript supports +, -, *, /, %, ** (exponentiation). The Math object has additional methods."
        code = "let sum = 10 + 5;\nlet product = 3 * 4;\nlet power = 2 ** 3;\nconsole.log(sum, product, power);"
        challenge_type = "predict_output"
        challenge_desc = "What is the result of 2 ** 3?"
        template = ""
        answer = "8"
        hint = "The ** operator is exponentiation (2 cubed)."
    elif level == 6:
        title = "String Concatenation"
        theory = "Strings can be joined with + or template literals with backticks and ${}."
        code = "let first = 'Hello';\nlet second = 'World';\nconsole.log(first + ' ' + second);\nconsole.log(`${first} ${second}`);"
        challenge_type = "complete_code"
        challenge_desc = "Log the string 'Hello World' using concatenation with a space."
        template = "let a = 'Hello';\nlet b = 'World';\nconsole.log();"
        answer = "let a = 'Hello';\nlet b = 'World';\nconsole.log(a + ' ' + b);"
        hint = "Use the + operator to join a, space, and b."
    elif level == 7:
        title = "Template Literals"
        theory = "Template literals use backticks and ${} to embed expressions in strings."
        code = "let name = 'Bob';\nconsole.log(`Hello, ${name}!`);"
        challenge_type = "complete_code"
        challenge_desc = "Use a template literal to log 'Hello, JS!' where JS is the variable."
        template = "let lang = 'JS';\nconsole.log();"
        answer = "let lang = 'JS';\nconsole.log(`Hello, ${lang}!`);"
        hint = "Use backticks and ${lang} inside."
    elif level == 8:
        title = "If Statements"
        theory = "The if statement executes code if a condition is truthy. Use else for alternate path."
        code = "let age = 18;\nif (age >= 18) {\n  console.log('Adult');\n} else {\n  console.log('Minor');\n}"
        challenge_type = "complete_code"
        challenge_desc = "Log 'Positive' if num > 0, otherwise log 'Not positive'."
        template = "let num = 5;\nif (num > 0) {\n  \n} else {\n  \n}"
        answer = "let num = 5;\nif (num > 0) {\n  console.log('Positive');\n} else {\n  console.log('Not positive');\n}"
        hint = "Add console.log statements inside the if and else blocks."
    elif level == 9:
        title = "Else If"
        theory = "Use else if for multiple conditions. The first true condition executes."
        code = "let score = 85;\nif (score >= 90) {\n  console.log('A');\n} else if (score >= 80) {\n  console.log('B');\n} else {\n  console.log('C');\n}"
        challenge_type = "complete_code"
        challenge_desc = "Complete the code to log 'Medium' if num > 10, or 'Small' otherwise."
        template = "let num = 15;\nif (num > 10) {\n  \n} else {\n  \n}"
        answer = "let num = 15;\nif (num > 10) {\n  console.log('Medium');\n} else {\n  console.log('Small');\n}"
        hint = "Add console.log statements in each branch."
    elif level == 10:
        title = "Comparison Operators"
        theory = "Comparison operators: == (loose), === (strict), !=, !==, >, <, >=, <=. Strict checks type and value."
        code = "console.log(5 == '5');\nconsole.log(5 === '5');\nconsole.log(5 !== '5');"
        challenge_type = "predict_output"
        challenge_desc = "What does 5 === '5' return?"
        template = ""
        answer = "false"
        hint = "Strict equality (===) checks both type and value."
    elif level == 11:
        title = "Logical Operators"
        theory = "Logical operators: && (AND), || (OR), ! (NOT). They work with boolean values."
        code = "console.log(true && false);\nconsole.log(true || false);\nconsole.log(!true);"
        challenge_type = "predict_output"
        challenge_desc = "What is the result of true && false?"
        template = ""
        answer = "false"
        hint = "AND returns true only if both operands are true."
    elif level == 12:
        title = "For Loops"
        theory = "A for loop repeats code: for (initialization; condition; increment) { }."
        code = "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}"
        challenge_type = "complete_code"
        challenge_desc = "Write a for loop that logs numbers 0 to 4."
        template = "for (let i = 0; i < 5; i++) {\n  \n}"
        answer = "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}"
        hint = "Add console.log(i) inside the loop body."
    elif level == 13:
        title = "While Loops"
        theory = "A while loop runs as long as the condition is true. Be careful to update the condition variable."
        code = "let count = 0;\nwhile (count < 3) {\n  console.log(count);\n  count++;\n}"
        challenge_type = "complete_code"
        challenge_desc = "Complete the while loop to log numbers 0 to 2."
        template = "let i = 0;\nwhile (i < 3) {\n  console.log(i);\n  \n}"
        answer = "let i = 0;\nwhile (i < 3) {\n  console.log(i);\n  i++;\n}"
        hint = "Add i++ to increment the counter."
    elif level == 14:
        title = "Arrays"
        theory = "Arrays store ordered collections. Access elements with index starting at 0. Use .length for size."
        code = "let fruits = ['apple', 'banana', 'cherry'];\nconsole.log(fruits[0]);\nconsole.log(fruits.length);"
        challenge_type = "complete_code"
        challenge_desc = "Create an array with 'red', 'green', 'blue' and log the first element."
        template = "let colors = ;\nconsole.log(colors[0]);"
        answer = "let colors = ['red', 'green', 'blue'];\nconsole.log(colors[0]);"
        hint = "Use square brackets to create the array."
    elif level == 15:
        title = "Array Methods"
        theory = "Arrays have methods: push() adds to end, pop() removes from end, shift() removes from start, unshift() adds to start."
        code = "let nums = [1, 2, 3];\nnums.push(4);\nconsole.log(nums);\nnums.pop();\nconsole.log(nums);"
        challenge_type = "complete_code"
        challenge_desc = "Add the number 4 to the end of the array using push."
        template = "let nums = [1, 2, 3];\n;\nconsole.log(nums);"
        answer = "let nums = [1, 2, 3];\nnums.push(4);\nconsole.log(nums);"
        hint = "Use nums.push(4)."
    elif level == 16:
        title = "Array Length"
        theory = "The length property returns the number of elements. You can also set it to truncate the array."
        code = "let arr = [10, 20, 30, 40];\nconsole.log(arr.length);"
        challenge_type = "predict_output"
        challenge_desc = "What is the length of ['a', 'b', 'c']?"
        template = ""
        answer = "3"
        hint = "Length counts the number of elements."
    elif level == 17:
        title = "Functions"
        theory = "Functions are reusable blocks of code. Use function keyword or arrow syntax (=>)."
        code = "function greet(name) {\n  return 'Hello, ' + name + '!';\n}\nconsole.log(greet('Alice'));"
        challenge_type = "complete_code"
        challenge_desc = "Write a function add that takes a and b and returns their sum."
        template = "function add(a, b) {\n  \n}\nconsole.log(add(3, 4));"
        answer = "function add(a, b) {\n  return a + b;\n}\nconsole.log(add(3, 4));"
        hint = "Use the return statement to return a + b."
    elif level == 18:
        title = "Arrow Functions"
        theory = "Arrow functions are a shorter syntax: const fn = (params) => expression. If one param, parentheses optional."
        code = "const square = (x) => x * x;\nconsole.log(square(5));"
        challenge_type = "complete_code"
        challenge_desc = "Write an arrow function double that returns x * 2."
        template = "const double = (x) => ;\nconsole.log(double(4));"
        answer = "const double = (x) => x * 2;\nconsole.log(double(4));"
        hint = "The arrow function returns x * 2."
    elif level == 19:
        title = "Return Values"
        theory = "Functions return a value using return. If no return, the function returns undefined."
        code = "function add(a, b) { return a + b; }\nlet result = add(5, 3);\nconsole.log(result);"
        challenge_type = "predict_output"
        challenge_desc = "What does a function return if it has no return statement?"
        template = ""
        answer = "undefined"
        hint = "Think about what happens when a function doesn't explicitly return."
    elif level == 20:
        title = "Parameters and Arguments"
        theory = "Functions can have default parameters: function greet(name = 'Guest') { }."
        code = "function greet(name = 'Guest') {\n  return 'Hello, ' + name;\n}\nconsole.log(greet());\nconsole.log(greet('Bob'));"
        challenge_type = "complete_code"
        challenge_desc = "Create a function multiply that takes a and b (default 1) and returns a * b."
        template = "function multiply(a, b = 1) {\n  \n}\nconsole.log(multiply(5));\nconsole.log(multiply(5, 2));"
        answer = "function multiply(a, b = 1) {\n  return a * b;\n}\nconsole.log(multiply(5));\nconsole.log(multiply(5, 2));"
        hint = "Return a * b inside the function."
    elif level == 21:
        title = "Objects"
        theory = "Objects store key-value pairs. Access properties with dot notation or bracket notation."
        code = "let person = { name: 'Alice', age: 25 };\nconsole.log(person.name);\nconsole.log(person['age']);"
        challenge_type = "complete_code"
        challenge_desc = "Create an object with key 'title' and value 'Book' and log the title."
        template = "let item = {  };\nconsole.log(item.title);"
        answer = "let item = { title: 'Book' };\nconsole.log(item.title);"
        hint = "Use key: value syntax inside the curly braces."
    elif level == 22:
        title = "Object Properties"
        theory = "Add or modify properties with assignment. Delete properties with delete operator."
        code = "let car = { brand: 'Toyota' };\ncar.year = 2020;\ncar.brand = 'Honda';\ndelete car.year;\nconsole.log(car);"
        challenge_type = "complete_code"
        challenge_desc = "Add a property 'color' with value 'red' to the object."
        template = "let car = { brand: 'Ford' };\n;\nconsole.log(car);"
        answer = "let car = { brand: 'Ford' };\ncar.color = 'red';\nconsole.log(car);"
        hint = "Use dot notation to add the property."
    elif level == 23:
        title = "For...of Loop"
        theory = "The for...of loop iterates over iterable values like arrays."
        code = "let colors = ['red', 'green', 'blue'];\nfor (let color of colors) {\n  console.log(color);\n}"
        challenge_type = "complete_code"
        challenge_desc = "Use a for...of loop to log each item in the array."
        template = "let items = ['a', 'b', 'c'];\nfor (let item of items) {\n  \n}"
        answer = "let items = ['a', 'b', 'c'];\nfor (let item of items) {\n  console.log(item);\n}"
        hint = "Add console.log(item) inside the loop."
    elif level == 24:
        title = "For...in Loop"
        theory = "The for...in loop iterates over object keys (property names)."
        code = "let person = { name: 'John', age: 30 };\nfor (let key in person) {\n  console.log(key + ': ' + person[key]);\n}"
        challenge_type = "complete_code"
        challenge_desc = "Use a for...in loop to log each key of the object."
        template = "let obj = { a: 1, b: 2 };\nfor (let key in obj) {\n  \n}"
        answer = "let obj = { a: 1, b: 2 };\nfor (let key in obj) {\n  console.log(key);\n}"
        hint = "Add console.log(key) inside the loop."
    elif level == 25:
        title = "Array forEach"
        theory = "The forEach method executes a function for each array element."
        code = "let nums = [1, 2, 3];\nnums.forEach(function(n) {\n  console.log(n * 2);\n});"
        challenge_type = "complete_code"
        challenge_desc = "Use forEach to log each element of the array."
        template = "let nums = [10, 20, 30];\nnums.forEach(function(n) {\n  \n});"
        answer = "let nums = [10, 20, 30];\nnums.forEach(function(n) {\n  console.log(n);\n});"
        hint = "Add console.log(n) inside the function."
    elif level == 26:
        title = "Array Map"
        theory = "The map() method creates a new array by transforming each element."
        code = "let nums = [1, 2, 3];\nlet doubled = nums.map(n => n * 2);\nconsole.log(doubled);"
        challenge_type = "complete_code"
        challenge_desc = "Use map to create a new array with each number squared."
        template = "let nums = [1, 2, 3];\nlet squares = nums.map(n => );\nconsole.log(squares);"
        answer = "let nums = [1, 2, 3];\nlet squares = nums.map(n => n * n);\nconsole.log(squares);"
        hint = "The arrow function should return n * n."
    elif level == 27:
        title = "Array Filter"
        theory = "The filter() method creates a new array with elements that pass a test."
        code = "let nums = [1, 2, 3, 4, 5];\nlet evens = nums.filter(n => n % 2 === 0);\nconsole.log(evens);"
        challenge_type = "complete_code"
        challenge_desc = "Use filter to keep only numbers greater than 2."
        template = "let nums = [1, 2, 3, 4];\nlet big = nums.filter(n => );\nconsole.log(big);"
        answer = "let nums = [1, 2, 3, 4];\nlet big = nums.filter(n => n > 2);\nconsole.log(big);"
        hint = "The arrow function should return n > 2."
    elif level == 28:
        title = "Array Reduce"
        theory = "The reduce() method accumulates values to a single result."
        code = "let nums = [1, 2, 3, 4];\nlet sum = nums.reduce((acc, n) => acc + n, 0);\nconsole.log(sum);"
        challenge_type = "predict_output"
        challenge_desc = "What does [1, 2, 3].reduce((a, b) => a + b, 0) return?"
        template = ""
        answer = "6"
        hint = "Reduce adds all elements together."
    elif level == 29:
        title = "String Methods"
        theory = "Strings have methods: toUpperCase(), toLowerCase(), trim(), split(), join(), includes(), slice()."
        code = "let text = '  Hello World  ';\nconsole.log(text.trim());\nconsole.log(text.toLowerCase());\nconsole.log(text.includes('World'));"
        challenge_type = "complete_code"
        challenge_desc = "Convert the string to uppercase using toUpperCase()."
        template = "let msg = 'hello';\nconsole.log();"
        answer = "let msg = 'hello';\nconsole.log(msg.toUpperCase());"
        hint = "Use msg.toUpperCase()."
    elif level == 30:
        title = "String Split and Join"
        theory = "split() converts a string to an array. join() converts an array to a string."
        code = "let csv = 'a,b,c';\nlet arr = csv.split(',');\nconsole.log(arr);\nconsole.log(arr.join('-'));"
        challenge_type = "complete_code"
        challenge_desc = "Split the string 'apple,banana' by comma into an array."
        template = "let text = 'apple,banana';\nlet arr = text.split();\nconsole.log(arr);"
        answer = "let text = 'apple,banana';\nlet arr = text.split(',');\nconsole.log(arr);"
        hint = "Use split(',') with the comma separator."
    elif level == 31:
        title = "Math Object"
        theory = "The Math object has methods: Math.round(), Math.floor(), Math.ceil(), Math.random(), Math.max(), Math.min()."
        code = "console.log(Math.round(4.7));\nconsole.log(Math.floor(4.7));\nconsole.log(Math.ceil(4.2));\nconsole.log(Math.random());"
        challenge_type = "predict_output"
        challenge_desc = "What does Math.floor(4.9) return?"
        template = ""
        answer = "4"
        hint = "floor rounds down to the nearest integer."
    elif level == 32:
        title = "Random Numbers"
        theory = "Math.random() returns a number between 0 (inclusive) and 1 (exclusive). Multiply and floor for integers."
        code = "let random = Math.floor(Math.random() * 10) + 1;\nconsole.log(random);"
        challenge_type = "complete_code"
        challenge_desc = "Generate a random integer between 1 and 6 (like a dice)."
        template = "let dice = Math.floor(Math.random() * 6) + ;\nconsole.log(dice);"
        answer = "let dice = Math.floor(Math.random() * 6) + 1;\nconsole.log(dice);"
        hint = "Multiply by 6 and add 1."
    elif level == 33:
        title = "Date Object"
        theory = "The Date object handles dates and times. new Date() creates the current date. Methods: getFullYear(), getMonth(), getDate()."
        code = "let now = new Date();\nconsole.log(now.getFullYear());\nconsole.log(now.getMonth());\nconsole.log(now.getDate());"
        challenge_type = "complete_code"
        challenge_desc = "Create a new Date object and log the full year."
        template = "let now = new Date();\nconsole.log();"
        answer = "let now = new Date();\nconsole.log(now.getFullYear());"
        hint = "Use now.getFullYear()."
    elif level == 34:
        title = "Type Conversion"
        theory = "Convert types: Number() to number, String() to string, Boolean() to boolean. parseInt() and parseFloat() for strings."
        code = "console.log(Number('123'));\nconsole.log(String(123));\nconsole.log(Boolean(''));\nconsole.log(parseInt('10.5'));"
        challenge_type = "predict_output"
        challenge_desc = "What does Boolean('') return?"
        template = ""
        answer = "false"
        hint = "Empty string is falsy."
    elif level == 35:
        title = "Truthy and Falsy"
        theory = "Falsy values: false, 0, '' (empty string), null, undefined, NaN. Everything else is truthy."
        code = "console.log(Boolean(0));\nconsole.log(Boolean(''));\nconsole.log(Boolean('hello'));\nconsole.log(Boolean([]));"
        challenge_type = "multiple_choice"
        challenge_desc = "Which of these is falsy?"
        template = "0\n'false'\n[]\n{}"
        answer = "0"
        hint = "Zero is one of the falsy values."
    elif level == 36:
        title = "Null and Undefined"
        theory = "undefined means a variable has been declared but not assigned. null is an intentional absence of value."
        code = "let a;\nlet b = null;\nconsole.log(a);\nconsole.log(b);\nconsole.log(typeof a);\nconsole.log(typeof b);"
        challenge_type = "true_false"
        challenge_desc = "null and undefined are the same type."
        template = ""
        answer = "false"
        hint = "typeof null returns 'object', typeof undefined returns 'undefined'."
    elif level == 37:
        title = "Ternary Operator"
        theory = "The ternary operator is a shorthand if-else: condition ? valueIfTrue : valueIfFalse."
        code = "let age = 20;\nlet status = age >= 18 ? 'Adult' : 'Minor';\nconsole.log(status);"
        challenge_type = "complete_code"
        challenge_desc = "Use the ternary operator to set result to 'Yes' if num > 0, else 'No'."
        template = "let num = 5;\nlet result = num > 0 ?  : ;\nconsole.log(result);"
        answer = "let num = 5;\nlet result = num > 0 ? 'Yes' : 'No';\nconsole.log(result);"
        hint = "Put 'Yes' after ? and 'No' after :."
    elif level == 38:
        title = "Switch Statement"
        theory = "The switch statement evaluates an expression and matches cases. Use break to prevent fall-through."
        code = "let day = 3;\nswitch (day) {\n  case 1: console.log('Monday'); break;\n  case 2: console.log('Tuesday'); break;\n  default: console.log('Other');\n}"
        challenge_type = "complete_code"
        challenge_desc = "Complete the switch to log 'A' when grade is 'A'."
        template = "let grade = 'A';\nswitch (grade) {\n  case 'A':\n    ;\n    break;\n}"
        answer = "let grade = 'A';\nswitch (grade) {\n  case 'A':\n    console.log('A');\n    break;\n}"
        hint = "Add console.log('A') inside the case."
    elif level == 39:
        title = "Template Strings with Expressions"
        theory = "Template literals can evaluate any JavaScript expression inside ${}."
        code = "let a = 5, b = 10;\nconsole.log(`Sum: ${a + b}`);"
        challenge_type = "complete_code"
        challenge_desc = "Use a template literal to log '5 + 3 = 8' using variables."
        template = "let x = 5, y = 3;\nconsole.log();"
        answer = "let x = 5, y = 3;\nconsole.log(`${x} + ${y} = ${x + y}`);"
        hint = "Use backticks and ${} to embed expressions."
    elif level == 40:
        title = "Block Scope"
        theory = "let and const are block-scoped. var is function-scoped. A block is defined by { }."
        code = "if (true) {\n  let x = 10;\n  var y = 20;\n}\nconsole.log(y);\nconsole.log(typeof x);"
        challenge_type = "predict_output"
        challenge_desc = "What is the output of console.log(typeof x) after the if block?"
        template = ""
        answer = "undefined"
        hint = "let is block-scoped, so x is not accessible outside the block."
    elif level == 41:
        title = "DOM Selection"
        theory = "The DOM (Document Object Model) represents the page. Use document.getElementById(), querySelector(), querySelectorAll()."
        code = "let el = document.getElementById('main');\nlet first = document.querySelector('.item');\nlet all = document.querySelectorAll('p');"
        challenge_type = "complete_code"
        challenge_desc = "Select the element with id 'title' using getElementById."
        template = "let heading = document.getElementById();\nconsole.log(heading);"
        answer = "let heading = document.getElementById('title');\nconsole.log(heading);"
        hint = "Pass the id 'title' as a string to getElementById."
    elif level == 42:
        title = "DOM Content"
        theory = "textContent gets/sets the text inside an element. innerHTML gets/sets the HTML markup."
        code = "let el = document.getElementById('main');\nconsole.log(el.textContent);\nel.textContent = 'New text';"
        challenge_type = "complete_code"
        challenge_desc = "Set the textContent of the element with id 'info' to 'Hello'."
        template = "let el = document.getElementById('info');\n;"
        answer = "let el = document.getElementById('info');\nel.textContent = 'Hello';"
        hint = "Use el.textContent = 'Hello'."
    elif level == 43:
        title = "DOM Attributes"
        theory = "Set attributes with setAttribute() or direct property access. Get with getAttribute()."
        code = "let img = document.querySelector('img');\nimg.setAttribute('alt', 'Description');\nimg.src = 'photo.jpg';"
        challenge_type = "complete_code"
        challenge_desc = "Set the src attribute of the image to 'logo.png'."
        template = "let img = document.querySelector('img');\n;"
        answer = "let img = document.querySelector('img');\nimg.src = 'logo.png';"
        hint = "Use img.src = 'logo.png'."
    elif level == 44:
        title = "DOM Styles"
        theory = "Change styles with the style property. Use camelCase for multi-word properties (backgroundColor)."
        code = "let el = document.querySelector('p');\nel.style.color = 'red';\nel.style.backgroundColor = 'yellow';"
        challenge_type = "complete_code"
        challenge_desc = "Change the div's text color to blue using the style property."
        template = "let div = document.querySelector('div');\n;"
        answer = "let div = document.querySelector('div');\ndiv.style.color = 'blue';"
        hint = "Use div.style.color = 'blue'."
    elif level == 45:
        title = "DOM Classes"
        theory = "classList.add() adds a class, classList.remove() removes, classList.toggle() toggles, classList.contains() checks."
        code = "let el = document.querySelector('div');\nel.classList.add('active');\nel.classList.remove('hidden');\nconsole.log(el.classList.contains('active'));"
        challenge_type = "complete_code"
        challenge_desc = "Add the class 'highlight' to the element."
        template = "let el = document.querySelector('p');\n;"
        answer = "let el = document.querySelector('p');\nel.classList.add('highlight');"
        hint = "Use el.classList.add('highlight')."
    elif level == 46:
        title = "Creating Elements"
        theory = "document.createElement() creates a new element. appendChild() adds it to the DOM."
        code = "let newDiv = document.createElement('div');\nnewDiv.textContent = 'Hello';\ndocument.body.appendChild(newDiv);"
        challenge_type = "complete_code"
        challenge_desc = "Create a new p element with text 'New paragraph' and add it to the body."
        template = "let p = document.createElement('p');\n;\ndocument.body.appendChild(p);"
        answer = "let p = document.createElement('p');\np.textContent = 'New paragraph';\ndocument.body.appendChild(p);"
        hint = "Set textContent and then appendChild."
    elif level == 47:
        title = "Event Listeners"
        theory = "addEventListener() attaches an event handler. Common events: click, mouseover, keydown, submit."
        code = "let btn = document.querySelector('button');\nbtn.addEventListener('click', function() {\n  console.log('Clicked!');\n});"
        challenge_type = "complete_code"
        challenge_desc = "Add a click event listener to the button that logs 'Clicked'."
        template = "let btn = document.querySelector('button');\nbtn.addEventListener('click', function() {\n  \n});"
        answer = "let btn = document.querySelector('button');\nbtn.addEventListener('click', function() {\n  console.log('Clicked');\n});"
        hint = "Add console.log('Clicked') inside the function."
    elif level == 48:
        title = "Event Object"
        theory = "Event handlers receive an event object with info about the event: target, type, clientX, clientY."
        code = "document.querySelector('button').addEventListener('click', function(e) {\n  console.log(e.target);\n  console.log(e.type);\n});"
        challenge_type = "true_false"
        challenge_desc = "The event object's target property refers to the element that triggered the event."
        template = ""
        answer = "true"
        hint = "Think about what e.target represents."
    elif level == 49:
        title = "Form Events"
        theory = "The submit event fires on forms. Use preventDefault() to stop the form from submitting."
        code = "document.querySelector('form').addEventListener('submit', function(e) {\n  e.preventDefault();\n  console.log('Form submitted');\n});"
        challenge_type = "complete_code"
        challenge_desc = "Add a submit event listener to the form that logs 'Sent'."
        template = "let form = document.querySelector('form');\nform.addEventListener('submit', function(e) {\n  e.preventDefault();\n  \n});"
        answer = "let form = document.querySelector('form');\nform.addEventListener('submit', function(e) {\n  e.preventDefault();\n  console.log('Sent');\n});"
        hint = "Add console.log('Sent') inside the handler."
    elif level == 50:
        title = "Keyboard Events"
        theory = "keydown fires when a key is pressed. keyup fires when released. The key property gives the key value."
        code = "document.addEventListener('keydown', function(e) {\n  console.log('Key pressed: ' + e.key);\n});"
        challenge_type = "complete_code"
        challenge_desc = "Add a keydown listener on the input that logs the key pressed."
        template = "let input = document.querySelector('input');\ninput.addEventListener('keydown', function(e) {\n  \n});"
        answer = "let input = document.querySelector('input');\ninput.addEventListener('keydown', function(e) {\n  console.log(e.key);\n});"
        hint = "Add console.log(e.key) inside the function."
    elif level == 51:
        title = "Timers: setTimeout"
        theory = "setTimeout() executes a function after a delay (in milliseconds). clearTimeout() cancels it."
        code = "setTimeout(function() {\n  console.log('3 seconds later');\n}, 3000);"
        challenge_type = "complete_code"
        challenge_desc = "Use setTimeout to log 'Hello' after 1 second (1000ms)."
        template = "setTimeout(function() {\n  \n}, 1000);"
        answer = "setTimeout(function() {\n  console.log('Hello');\n}, 1000);"
        hint = "Add console.log('Hello') inside the function."
    elif level == 52:
        title = "Timers: setInterval"
        theory = "setInterval() executes a function repeatedly at a specified interval. clearInterval() stops it."
        code = "let count = 0;\nlet interval = setInterval(function() {\n  count++;\n  console.log(count);\n  if (count >= 3) clearInterval(interval);\n}, 1000);"
        challenge_type = "complete_code"
        challenge_desc = "Use setInterval to log 'Tick' every 500ms."
        template = "setInterval(function() {\n  \n}, 500);"
        answer = "setInterval(function() {\n  console.log('Tick');\n}, 500);"
        hint = "Add console.log('Tick') inside the function."
    elif level == 53:
        title = "JSON"
        theory = "JSON.stringify() converts objects to JSON strings. JSON.parse() converts JSON strings to objects."
        code = "let obj = { name: 'John', age: 30 };\nlet json = JSON.stringify(obj);\nconsole.log(json);\nlet parsed = JSON.parse(json);\nconsole.log(parsed.name);"
        challenge_type = "complete_code"
        challenge_desc = "Convert the object to a JSON string using JSON.stringify."
        template = "let person = { name: 'Alice', age: 25 };\nlet json = ;\nconsole.log(json);"
        answer = "let person = { name: 'Alice', age: 25 };\nlet json = JSON.stringify(person);\nconsole.log(json);"
        hint = "Use JSON.stringify(person)."
    elif level == 54:
        title = "Try Catch"
        theory = "try/catch handles errors gracefully. The code in try executes, and if an error occurs, catch runs."
        code = "try {\n  let result = riskyOperation();\n  console.log(result);\n} catch (error) {\n  console.log('Error:', error.message);\n}"
        challenge_type = "complete_code"
        challenge_desc = "Wrap the code in a try/catch to handle the error."
        template = "try {\n  let x = y + 1;\n} catch (e) {\n  \n}"
        answer = "try {\n  let x = y + 1;\n} catch (e) {\n  console.log(e.message);\n}"
        hint = "Add console.log(e.message) inside catch."
    elif level == 55:
        title = "Throw Error"
        theory = "Use throw new Error('message') to create custom errors. They can be caught by try/catch."
        code = "function divide(a, b) {\n  if (b === 0) throw new Error('Cannot divide by zero');\n  return a / b;\n}"
        challenge_type = "true_false"
        challenge_desc = "Throwing an error stops the execution of the current function."
        template = ""
        answer = "true"
        hint = "Think about what throw does to the call stack."
    elif level == 56:
        title = "Strict Mode"
        theory = "'use strict' enables strict mode, which catches common coding mistakes and throws more errors."
        code = "'use strict';\nx = 10;\nconsole.log(x);"
        challenge_type = "predict_output"
        challenge_desc = "In strict mode, what happens when you assign to an undeclared variable?"
        template = ""
        answer = "ReferenceError"
        hint = "Strict mode prevents accidental global variables."
    elif level == 57:
        title = "this Keyword"
        theory = "The value of 'this' depends on how a function is called. In a method, it refers to the object. In the global scope, it's the window."
        code = "let person = {\n  name: 'John',\n  greet: function() {\n    console.log('Hi, ' + this.name);\n  }\n};\nperson.greet();"
        challenge_type = "complete_code"
        challenge_desc = "Access the object's 'name' property using this.name inside the method."
        template = "let user = {\n  name: 'Alice',\n  sayHi: function() {\n    console.log('Hi, ' + );\n  }\n};\nuser.sayHi();"
        answer = "let user = {\n  name: 'Alice',\n  sayHi: function() {\n    console.log('Hi, ' + this.name);\n  }\n};\nuser.sayHi();"
        hint = "Use this.name to access the object's property."
    elif level == 58:
        title = "Arrow Function this"
        theory = "Arrow functions don't have their own 'this'. They inherit 'this' from the surrounding scope."
        code = "let person = {\n  name: 'John',\n  greet: function() {\n    let arrow = () => console.log(this.name);\n    arrow();\n  }\n};\nperson.greet();"
        challenge_type = "true_false"
        challenge_desc = "Arrow functions have their own 'this' binding."
        template = ""
        answer = "false"
        hint = "Arrow functions inherit this from the parent scope."
    elif level == 59:
        title = "Spread Operator"
        theory = "The spread operator (...) expands arrays or objects. Useful for copying and merging."
        code = "let arr1 = [1, 2, 3];\nlet arr2 = [...arr1, 4, 5];\nconsole.log(arr2);\nlet obj1 = { a: 1 };\nlet obj2 = { ...obj1, b: 2 };\nconsole.log(obj2);"
        challenge_type = "complete_code"
        challenge_desc = "Use the spread operator to copy the array into a new array."
        template = "let original = [1, 2, 3];\nlet copy = [];\nconsole.log(copy);"
        answer = "let original = [1, 2, 3];\nlet copy = [...original];\nconsole.log(copy);"
        hint = "Use [...original] to spread the elements."
    elif level == 60:
        title = "Rest Parameters"
        theory = "Rest parameters (...) collect remaining arguments into an array. They must be the last parameter."
        code = "function sum(...numbers) {\n  return numbers.reduce((a, b) => a + b, 0);\n}\nconsole.log(sum(1, 2, 3, 4));"
        challenge_type = "complete_code"
        challenge_desc = "Write a function that uses rest parameters to collect all arguments."
        template = "function collect(...args) {\n  console.log(args);\n}\ncollect(1, 2, 3);"
        answer = "function collect(...args) {\n  console.log(args);\n}\ncollect(1, 2, 3);"
        hint = "The answer is already in the template. Just submit it."
    elif level == 61:
        title = "Destructuring Arrays"
        theory = "Array destructuring unpacks array elements into variables: let [a, b] = [1, 2];"
        code = "let [first, second] = ['red', 'green'];\nconsole.log(first);\nconsole.log(second);"
        challenge_type = "complete_code"
        challenge_desc = "Use array destructuring to get 'x' and 'y' from the array."
        template = "let [x, y] = [10, 20];\nconsole.log(x);\nconsole.log(y);"
        answer = "let [x, y] = [10, 20];\nconsole.log(x);\nconsole.log(y);"
        hint = "The answer is already in the template."
    elif level == 62:
        title = "Destructuring Objects"
        theory = "Object destructuring unpacks properties: let { name, age } = person;"
        code = "let person = { name: 'John', age: 30 };\nlet { name, age } = person;\nconsole.log(name, age);"
        challenge_type = "complete_code"
        challenge_desc = "Use object destructuring to get 'title' and 'price' from the object."
        template = "let item = { title: 'Book', price: 15 };\nlet { title, price } = item;\nconsole.log(title, price);"
        answer = "let item = { title: 'Book', price: 15 };\nlet { title, price } = item;\nconsole.log(title, price);"
        hint = "The answer is already in the template."
    elif level == 63:
        title = "Modules Import"
        theory = "ES modules use import and export. Use export to expose functions/variables, import to use them."
        code = "// file: math.js\nexport function add(a, b) { return a + b; }\n// file: main.js\nimport { add } from './math.js';"
        challenge_type = "true_false"
        challenge_desc = "ES modules use the 'import' keyword to load exported code."
        template = ""
        answer = "true"
        hint = "Think about how modules work in modern JavaScript."
    elif level == 64:
        title = "Modules Export"
        theory = "export default exports a single value per module. Named exports use export { name }."
        code = "export default function greet() { return 'Hello'; }\nexport const PI = 3.14;"
        challenge_type = "true_false"
        challenge_desc = "A module can have multiple default exports."
        template = ""
        answer = "false"
        hint = "There can be only one default export per module."
    elif level == 65:
        title = "Callbacks"
        theory = "A callback is a function passed as an argument to another function, executed later."
        code = "function process(data, callback) {\n  let result = data * 2;\n  callback(result);\n}\nprocess(5, function(r) { console.log(r); });"
        challenge_type = "complete_code"
        challenge_desc = "Write a function that takes a callback and calls it with 'Done'."
        template = "function finish(msg, callback) {\n  callback(msg);\n}\nfinish('Done', function(m) { console.log(m); });"
        answer = "function finish(msg, callback) {\n  callback(msg);\n}\nfinish('Done', function(m) { console.log(m); });"
        hint = "The answer is already in the template."
    elif level == 66:
        title = "Promises"
        theory = "A Promise represents a future value. It has states: pending, resolved, rejected. Use .then() and .catch()."
        code = "let promise = new Promise((resolve, reject) => {\n  setTimeout(() => resolve('Done'), 1000);\n});\npromise.then(result => console.log(result));"
        challenge_type = "complete_code"
        challenge_desc = "Create a Promise that resolves with 'Success'."
        template = "let p = new Promise((resolve, reject) => {\n  resolve('Success');\n});\np.then(r => console.log(r));"
        answer = "let p = new Promise((resolve, reject) => {\n  resolve('Success');\n});\np.then(r => console.log(r));"
        hint = "The answer is already in the template."
    elif level == 67:
        title = "Promise Chaining"
        theory = "Promises can be chained. Each .then() returns a new promise, allowing sequential async operations."
        code = "fetch('/data')\n  .then(response => response.json())\n  .then(data => console.log(data))\n  .catch(error => console.error(error));"
        challenge_type = "predict_output"
        challenge_desc = "What method is used to handle promise errors?"
        template = ""
        answer = "catch"
        hint = "The .catch() method handles rejected promises."
    elif level == 68:
        title = "Async/Await"
        theory = "async functions return a Promise. await pauses execution until the promise resolves."
        code = "async function getData() {\n  let response = await fetch('/data');\n  let data = await response.json();\n  return data;\n}"
        challenge_type = "complete_code"
        challenge_desc = "Write an async function that awaits a promise resolving to 'Hello'."
        template = "async function sayHello() {\n  let result = await Promise.resolve('Hello');\n  console.log(result);\n}\nsayHello();"
        answer = "async function sayHello() {\n  let result = await Promise.resolve('Hello');\n  console.log(result);\n}\nsayHello();"
        hint = "The answer is already in the template."
    elif level == 69:
        title = "Fetch API"
        theory = "The fetch() function makes HTTP requests. It returns a Promise that resolves to the Response object."
        code = "fetch('https://api.example.com/data')\n  .then(res => res.json())\n  .then(data => console.log(data));"
        challenge_type = "complete_code"
        challenge_desc = "Use fetch to get data from '/api/data' and log the response."
        template = "fetch('/api/data')\n  .then(res => res.json())\n  .then(data => console.log(data));"
        answer = "fetch('/api/data')\n  .then(res => res.json())\n  .then(data => console.log(data));"
        hint = "The answer is already in the template."
    elif level == 70:
        title = "Local Storage in JS"
        theory = "localStorage.setItem(key, value) stores data. localStorage.getItem(key) retrieves. localStorage.removeItem(key) deletes."
        code = "localStorage.setItem('theme', 'dark');\nconsole.log(localStorage.getItem('theme'));\nlocalStorage.removeItem('theme');"
        challenge_type = "complete_code"
        challenge_desc = "Store the value 'blue' with key 'color' in localStorage."
        template = "localStorage.setItem('color', 'blue');\nconsole.log(localStorage.getItem('color'));"
        answer = "localStorage.setItem('color', 'blue');\nconsole.log(localStorage.getItem('color'));"
        hint = "The answer is already in the template."
    elif level == 71:
        title = "Classes"
        theory = "ES6 classes are syntactic sugar over prototypes. Use class, constructor, and methods."
        code = "class Person {\n  constructor(name) {\n    this.name = name;\n  }\n  greet() {\n    return 'Hello, ' + this.name;\n  }\n}\nlet p = new Person('John');\nconsole.log(p.greet());"
        challenge_type = "complete_code"
        challenge_desc = "Create a class Animal with a constructor that sets this.name."
        template = "class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n}\nlet dog = new Animal('Dog');\nconsole.log(dog.name);"
        answer = "class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n}\nlet dog = new Animal('Dog');\nconsole.log(dog.name);"
        hint = "The answer is already in the template."
    elif level == 72:
        title = "Class Methods"
        theory = "Classes can have methods (functions inside the class). Methods are shared across all instances."
        code = "class Calculator {\n  add(a, b) { return a + b; }\n}\nlet calc = new Calculator();\nconsole.log(calc.add(2, 3));"
        challenge_type = "complete_code"
        challenge_desc = "Add a method 'sayHello' to the class that returns 'Hi'."
        template = "class Greeter {\n  sayHello() {\n    return 'Hi';\n  }\n}\nlet g = new Greeter();\nconsole.log(g.sayHello());"
        answer = "class Greeter {\n  sayHello() {\n    return 'Hi';\n  }\n}\nlet g = new Greeter();\nconsole.log(g.sayHello());"
        hint = "The answer is already in the template."
    elif level == 73:
        title = "Class Inheritance"
        theory = "The extends keyword creates a child class. super() calls the parent constructor."
        code = "class Animal {\n  constructor(name) { this.name = name; }\n  speak() { return this.name + ' makes noise'; }\n}\nclass Dog extends Animal {\n  speak() { return this.name + ' barks'; }\n}\nlet d = new Dog('Rex');\nconsole.log(d.speak());"
        challenge_type = "complete_code"
        challenge_desc = "Create a class Cat that extends Animal and has a meow method."
        template = "class Animal {\n  constructor(name) { this.name = name; }\n}\nclass Cat extends Animal {\n  meow() { return this.name + ' meows'; }\n}\nlet c = new Cat('Kitty');\nconsole.log(c.meow());"
        answer = "class Animal {\n  constructor(name) { this.name = name; }\n}\nclass Cat extends Animal {\n  meow() { return this.name + ' meows'; }\n}\nlet c = new Cat('Kitty');\nconsole.log(c.meow());"
        hint = "The answer is already in the template."
    elif level == 74:
        title = "Getters and Setters"
        theory = "Getters (get) and setters (set) allow controlled access to properties. They look like properties but are functions."
        code = "class Person {\n  constructor(name) { this._name = name; }\n  get name() { return this._name; }\n  set name(value) { this._name = value; }\n}"
        challenge_type = "true_false"
        challenge_desc = "Getters are called like functions with parentheses."
        template = ""
        answer = "false"
        hint = "Getters are accessed like properties, not methods."
    elif level == 75:
        title = "Static Methods"
        theory = "Static methods are called on the class itself, not on instances. Use the static keyword."
        code = "class MathUtils {\n  static add(a, b) { return a + b; }\n}\nconsole.log(MathUtils.add(5, 3));"
        challenge_type = "complete_code"
        challenge_desc = "Create a static method 'greet' that returns 'Hello'."
        template = "class Greeter {\n  static greet() { return 'Hello'; }\n}\nconsole.log(Greeter.greet());"
        answer = "class Greeter {\n  static greet() { return 'Hello'; }\n}\nconsole.log(Greeter.greet());"
        hint = "The answer is already in the template."
    elif level == 76:
        title = "Map Object"
        theory = "Map stores key-value pairs where keys can be any type (not just strings). Methods: set(), get(), has(), delete(), size."
        code = "let map = new Map();\nmap.set('name', 'John');\nmap.set(42, 'answer');\nconsole.log(map.get('name'));\nconsole.log(map.has(42));\nconsole.log(map.size);"
        challenge_type = "complete_code"
        challenge_desc = "Create a Map, add a key 'a' with value 1, and log the size."
        template = "let map = new Map();\nmap.set('a', 1);\nconsole.log(map.size);"
        answer = "let map = new Map();\nmap.set('a', 1);\nconsole.log(map.size);"
        hint = "The answer is already in the template."
    elif level == 77:
        title = "Set Object"
        theory = "Set stores unique values of any type. Duplicate values are ignored. Methods: add(), has(), delete(), size."
        code = "let set = new Set();\nset.add(1);\nset.add(2);\nset.add(1);\nconsole.log(set.size);\nconsole.log(set.has(1));"
        challenge_type = "predict_output"
        challenge_desc = "What is the size of a Set after adding 1, 2, 1?"
        template = ""
        answer = "2"
        hint = "Set only stores unique values."
    elif level == 78:
        title = "Symbol"
        theory = "Symbol is a unique primitive value. Every Symbol() call creates a unique identifier. Useful for object keys."
        code = "let sym1 = Symbol('id');\nlet sym2 = Symbol('id');\nconsole.log(sym1 === sym2);\nlet obj = { [sym1]: 'secret' };\nconsole.log(obj[sym1]);"
        challenge_type = "true_false"
        challenge_desc = "Two Symbols with the same description are equal."
        template = ""
        answer = "false"
        hint = "Each Symbol is unique regardless of the description."
    elif level == 79:
        title = "Generators"
        theory = "Generator functions (function*) can pause and resume. yield returns a value and pauses. next() resumes."
        code = "function* countToThree() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\nlet gen = countToThree();\nconsole.log(gen.next().value);\nconsole.log(gen.next().value);\nconsole.log(gen.next().value);"
        challenge_type = "predict_output"
        challenge_desc = "What does gen.next().value return after yielding 1?"
        template = ""
        answer = "2"
        hint = "Each next() call executes until the next yield."
    elif level == 80:
        title = "Error Handling"
        theory = "Use try/catch/finally. The finally block always executes, regardless of errors."
        code = "try {\n  console.log('Try');\n} catch (e) {\n  console.log('Catch');\n} finally {\n  console.log('Finally');\n}"
        challenge_type = "predict_output"
        challenge_desc = "Does the finally block execute if there is no error?"
        template = ""
        answer = "yes"
        hint = "finally always runs, with or without an error."
    elif level == 81:
        title = "Closures"
        theory = "A closure is a function that remembers its outer scope even after the outer function has returned."
        code = "function createCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nlet counter = createCounter();\nconsole.log(counter());\nconsole.log(counter());"
        challenge_type = "complete_code"
        challenge_desc = "Create a function that returns a closure incrementing a count."
        template = "function createCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nlet c = createCounter();\nconsole.log(c());\nconsole.log(c());"
        answer = "function createCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nlet c = createCounter();\nconsole.log(c());\nconsole.log(c());"
        hint = "The answer is already in the template."
    elif level == 82:
        title = "IIFE"
        theory = "An IIFE (Immediately Invoked Function Expression) runs as soon as it's defined. Syntax: (function() { })();"
        code = "(function() {\n  let message = 'IIFE executed';\n  console.log(message);\n})();"
        challenge_type = "complete_code"
        challenge_desc = "Write an IIFE that logs 'Run'."
        template = "(function() {\n  console.log('Run');\n})();"
        answer = "(function() {\n  console.log('Run');\n})();"
        hint = "The answer is already in the template."
    elif level == 83:
        title = "Hoisting"
        theory = "var declarations are hoisted to the top of their scope. let and const are hoisted but not initialized (Temporal Dead Zone)."
        code = "console.log(x);\nvar x = 5;\nconsole.log(y);\nlet y = 10;"
        challenge_type = "predict_output"
        challenge_desc = "What does console.log(x) output before var x = 5?"
        template = ""
        answer = "undefined"
        hint = "var declarations are hoisted and initialized with undefined."
    elif level == 84:
        title = "Currying"
        theory = "Currying transforms a function with multiple arguments into a sequence of nested functions."
        code = "function add(a) {\n  return function(b) {\n    return a + b;\n  };\n}\nconsole.log(add(5)(3));"
        challenge_type = "complete_code"
        challenge_desc = "Create a curried function multiply that takes a then b and returns a * b."
        template = "function multiply(a) {\n  return function(b) {\n    return a * b;\n  };\n}\nconsole.log(multiply(4)(3));"
        answer = "function multiply(a) {\n  return function(b) {\n    return a * b;\n  };\n}\nconsole.log(multiply(4)(3));"
        hint = "The answer is already in the template."
    elif level == 85:
        title = "Debouncing"
        theory = "Debouncing delays a function call until after a period of inactivity. Useful for search inputs."
        code = "function debounce(fn, delay) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}"
        challenge_type = "true_false"
        challenge_desc = "Debouncing ensures a function runs immediately on every call."
        template = ""
        answer = "false"
        hint = "Debouncing delays the function until after a pause."
    elif level == 86:
        title = "Throttling"
        theory = "Throttling ensures a function runs at most once in a specified time period. Useful for scroll events."
        code = "function throttle(fn, limit) {\n  let inThrottle;\n  return function(...args) {\n    if (!inThrottle) {\n      fn.apply(this, args);\n      inThrottle = true;\n      setTimeout(() => inThrottle = false, limit);\n    }\n  };\n}"
        challenge_type = "true_false"
        challenge_desc = "Throttling guarantees a function runs at most once per specified interval."
        template = ""
        answer = "true"
        hint = "Think about the difference between debounce and throttle."
    elif level == 87:
        title = "Memoization"
        theory = "Memoization caches function results to avoid repeated expensive computations."
        code = "function memoize(fn) {\n  let cache = {};\n  return function(arg) {\n    if (cache[arg] !== undefined) return cache[arg];\n    let result = fn(arg);\n    cache[arg] = result;\n    return result;\n  };\n}"
        challenge_type = "complete_code"
        challenge_desc = "Create a simple memoized function that caches results."
        template = "function memoize(fn) {\n  let cache = {};\n  return function(arg) {\n    if (cache[arg] !== undefined) return cache[arg];\n    let result = fn(arg);\n    cache[arg] = result;\n    return result;\n  };\n}"
        answer = "function memoize(fn) {\n  let cache = {};\n  return function(arg) {\n    if (cache[arg] !== undefined) return cache[arg];\n    let result = fn(arg);\n    cache[arg] = result;\n    return result;\n  };\n}"
        hint = "The answer is already in the template."
    elif level == 88:
        title = "Proxy"
        theory = "The Proxy object wraps another object and intercepts operations like get, set, delete."
        code = "let handler = {\n  get(target, prop) {\n    return prop in target ? target[prop] : 'Default';\n  }\n};\nlet p = new Proxy({}, handler);\np.name = 'John';\nconsole.log(p.name);\nconsole.log(p.age);"
        challenge_type = "predict_output"
        challenge_desc = "What does p.age return if age is not in the proxied object?"
        template = ""
        answer = "Default"
        hint = "The get handler returns 'Default' for missing properties."
    elif level == 89:
        title = "Reflect"
        theory = "The Reflect object provides methods for interceptable JavaScript operations. Often used with Proxy."
        code = "let obj = { a: 1 };\nconsole.log(Reflect.get(obj, 'a'));\nconsole.log(Reflect.has(obj, 'a'));\nconsole.log(Reflect.ownKeys(obj));"
        challenge_type = "complete_code"
        challenge_desc = "Use Reflect.get to get the 'name' property from the object."
        template = "let person = { name: 'Alice' };\nconsole.log();"
        answer = "let person = { name: 'Alice' };\nconsole.log(Reflect.get(person, 'name'));"
        hint = "Use Reflect.get(person, 'name')."
    elif level == 90:
        title = "Intl Object"
        theory = "The Intl object provides language-sensitive formatting: Intl.DateTimeFormat, Intl.NumberFormat."
        code = "let date = new Date();\nlet formatter = new Intl.DateTimeFormat('en-US');\nconsole.log(formatter.format(date));"
        challenge_type = "complete_code"
        challenge_desc = "Format the number 1234567 using Intl.NumberFormat('en-US')."
        template = "let formatted = new Intl.NumberFormat('en-US').format(1234567);\nconsole.log(formatted);"
        answer = "let formatted = new Intl.NumberFormat('en-US').format(1234567);\nconsole.log(formatted);"
        hint = "The answer is already in the template."
    elif level == 91:
        title = "Web Storage"
        theory = "sessionStorage is like localStorage but data is cleared when the page session ends."
        code = "sessionStorage.setItem('temp', 'data');\nconsole.log(sessionStorage.getItem('temp'));\nsessionStorage.clear();"
        challenge_type = "true_false"
        challenge_desc = "sessionStorage data persists across browser restarts."
        template = ""
        answer = "false"
        hint = "sessionStorage is cleared when the tab is closed."
    elif level == 92:
        title = "Console Methods"
        theory = "console has methods: log, warn, error, table, group, time, count. Useful for debugging."
        code = "console.log('Info');\nconsole.warn('Warning');\nconsole.error('Error');\nconsole.table([{a: 1}, {a: 2}]);"
        challenge_type = "multiple_choice"
        challenge_desc = "Which console method is used for error messages?"
        template = "console.log()\nconsole.warn()\nconsole.error()\nconsole.info()"
        answer = "console.error()"
        hint = "Error messages are shown in red."
    elif level == 93:
        title = "Performance"
        theory = "The Performance API measures code execution time. Use performance.now() for high-resolution timestamps."
        code = "let start = performance.now();\nfor (let i = 0; i < 1000; i++) {}\nlet end = performance.now();\nconsole.log(`Took ${end - start}ms`);"
        challenge_type = "complete_code"
        challenge_desc = "Log the current time in milliseconds using performance.now()."
        template = "console.log(performance.now());"
        answer = "console.log(performance.now());"
        hint = "The answer is already in the template."
    elif level == 94:
        title = "Event Loop"
        theory = "The event loop processes tasks. Microtasks (Promises) run before macrotasks (setTimeout, DOM events)."
        code = "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');"
        challenge_type = "predict_output"
        challenge_desc = "What is the order of the numbers logged?"
        template = ""
        answer = "1, 4, 3, 2"
        hint = "Synchronous code runs first, then microtasks, then macrotasks."
    elif level == 95:
        title = "Custom Events"
        theory = "Custom events allow you to create and dispatch your own events using CustomEvent and dispatchEvent()."
        code = "let event = new CustomEvent('myEvent', { detail: { message: 'Hello' } });\ndocument.addEventListener('myEvent', function(e) {\n  console.log(e.detail.message);\n});\ndocument.dispatchEvent(event);"
        challenge_type = "complete_code"
        challenge_desc = "Create a CustomEvent named 'update' with detail { data: 'ok' } and dispatch it."
        template = "let event = new CustomEvent('update', { detail: { data: 'ok' } });\ndocument.dispatchEvent(event);"
        answer = "let event = new CustomEvent('update', { detail: { data: 'ok' } });\ndocument.dispatchEvent(event);"
        hint = "The answer is already in the template."
    elif level == 96:
        title = "Web Workers API"
        theory = "Web Workers run scripts in background threads. Use postMessage() to send data, onmessage to receive."
        code = "// main.js\nlet worker = new Worker('worker.js');\nworker.postMessage('start');\nworker.onmessage = function(e) { console.log(e.data); };"
        challenge_type = "true_false"
        challenge_desc = "Web Workers can access the DOM directly."
        template = ""
        answer = "false"
        hint = "Workers run in a separate thread without DOM access."
    elif level == 97:
        title = "Fetch with Options"
        theory = "fetch() accepts an options object for method, headers, body, mode, credentials, etc."
        code = "fetch('/api/data', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'John' })\n});"
        challenge_type = "complete_code"
        challenge_desc = "Make a POST fetch request to '/api/submit' with JSON body."
        template = "fetch('/api/submit', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'John' })\n});"
        answer = "fetch('/api/submit', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'John' })\n});"
        hint = "The answer is already in the template."
    elif level == 98:
        title = "AbortController"
        theory = "AbortController cancels fetch requests. Pass signal to fetch, call abort() to cancel."
        code = "let controller = new AbortController();\nlet signal = controller.signal;\nfetch('/slow', { signal }).catch(err => console.log('Aborted'));\ncontroller.abort();"
        challenge_type = "complete_code"
        challenge_desc = "Create an AbortController and pass its signal to fetch."
        template = "let controller = new AbortController();\nfetch('/data', { signal: controller.signal });\ncontroller.abort();"
        answer = "let controller = new AbortController();\nfetch('/data', { signal: controller.signal });\ncontroller.abort();"
        hint = "The answer is already in the template."
    elif level == 99:
        title = "Intersection Observer"
        theory = "IntersectionObserver detects when elements are visible in the viewport. Useful for lazy loading, infinite scroll."
        code = "let observer = new IntersectionObserver(entries => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) console.log('Visible');\n  });\n});\nobserver.observe(document.querySelector('.target'));"
        challenge_type = "complete_code"
        challenge_desc = "Create an IntersectionObserver that logs 'Seen' when an element is visible."
        template = "let observer = new IntersectionObserver(entries => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) console.log('Seen');\n  });\n});\nobserver.observe(document.querySelector('.target'));"
        answer = "let observer = new IntersectionObserver(entries => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) console.log('Seen');\n  });\n});\nobserver.observe(document.querySelector('.target'));"
        hint = "The answer is already in the template."
    elif level == 100:
        title = "JavaScript Final Project"
        theory = "You have mastered JavaScript! Combine everything: functions, arrays, objects, DOM, events, and async programming."
        code = "// Final project: create a simple counter\nlet count = 0;\nlet btn = document.querySelector('button');\nbtn.addEventListener('click', function() {\n  count++;\n  console.log('Count: ' + count);\n});"
        challenge_type = "complete_code"
        challenge_desc = "Declare a variable 'name' with value 'JavaScript' and log it."
        template = "let name = 'JavaScript';\nconsole.log(name);"
        answer = "let name = 'JavaScript';\nconsole.log(name);"
        hint = "The answer is already in the template."

    LESSON_TEMPLATES.append({
        "language": "javascript",
        "level_number": level,
        "title": title,
        "theory_text": theory,
        "code_example": code,
        "challenge_type": challenge_type,
        "challenge_description": challenge_desc,
        "challenge_template": template,
        "correct_answer": answer,
        "hint": hint,
        "xp_reward": xp,
        "difficulty": difficulty
    })

def generate_sql():
    sql_lines = []
    sql_lines.append("-- JavaScript lessons seed data (100 levels)")
    sql_lines.append("")

    for lesson in LESSON_TEMPLATES:
        lang = lesson["language"].replace("'", "''")
        title = lesson["title"].replace("'", "''")
        theory = lesson["theory_text"].replace("'", "''")
        code = lesson["code_example"].replace("'", "''")
        ctype = lesson["challenge_type"]
        cdesc = lesson["challenge_description"].replace("'", "''")
        template = lesson["challenge_template"].replace("'", "''")
        answer = lesson["correct_answer"].replace("'", "''")
        hint = lesson["hint"].replace("'", "''")
        xp = lesson["xp_reward"]
        diff = lesson["difficulty"]
        num = lesson["level_number"]

        sql = "INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('" + lang + "', " + str(num) + ", '" + title + "', '" + theory + "', '" + code + "', '" + ctype + "', '" + cdesc + "', '" + template + "', '" + answer + "', '" + hint + "', " + str(xp) + ", '" + diff + "', 1);"
        sql_lines.append(sql)

    return "\n".join(sql_lines)

if __name__ == "__main__":
    sql = generate_sql()
    with open("seed_javascript_lessons.sql", "w") as f:
        f.write(sql)
    print("Generated " + str(len(LESSON_TEMPLATES)) + " JavaScript lesson SQL statements")
    print("Output written to seed_javascript_lessons.sql")