#!/usr/bin/env python3

LESSON_TEMPLATES = []

for i in range(1, 101):
    level = i
    if level <= 20:
        difficulty = "easy"
        xp = 50
    elif level <= 50:
        difficulty = "medium"
        xp = 75
    elif level <= 80:
        difficulty = "hard"
        xp = 100
    else:
        difficulty = "hard"
        xp = 150

    if level == 1:
        title = "Basic HTML Structure"
        theory = "HTML stands for HyperText Markup Language. Every HTML document starts with a doctype declaration and has html, head, and body elements."
        code = "<!DOCTYPE html>\n<html>\n<head>\n  <title>My Page</title>\n</head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>"
        challenge_type = "complete_code"
        challenge_desc = "Add a title tag with the text 'My Page' inside the head section."
        template = "<!DOCTYPE html>\n<html>\n<head>\n  \n</head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>"
        answer = "<!DOCTYPE html>\n<html>\n<head>\n  <title>My Page</title>\n</head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>"
        hint = "The title tag goes inside the head section."
    elif level == 2:
        title = "Headings"
        theory = "HTML provides six heading levels from h1 to h6. h1 is the most important, h6 is the least important."
        code = "<h1>Main Heading</h1>\n<h2>Subheading</h2>\n<h3>Section</h3>"
        challenge_type = "complete_code"
        challenge_desc = "Add an h2 heading with the text 'Subtitle' below the h1."
        template = "<h1>Main Title</h1>\n\n<p>Some content</p>"
        answer = "<h1>Main Title</h1>\n<h2>Subtitle</h2>\n<p>Some content</p>"
        hint = "Use the h2 tag for subheadings."
    elif level == 3:
        title = "Paragraphs"
        theory = "The p tag defines a paragraph. Browsers automatically add some space before and after each paragraph."
        code = "<p>This is a paragraph.</p>\n<p>This is another paragraph.</p>"
        challenge_type = "complete_code"
        challenge_desc = "Add a paragraph tag with the text 'Hello World' inside the body."
        template = "<body>\n  \n</body>"
        answer = "<body>\n  <p>Hello World</p>\n</body>"
        hint = "Wrap the text in p tags."
    elif level == 4:
        title = "Text Formatting"
        theory = "HTML provides tags for text formatting: strong for bold, em for italic, u for underline, mark for highlighted."
        code = "<p><strong>Bold</strong> and <em>italic</em> text.</p>"
        challenge_type = "complete_code"
        challenge_desc = "Wrap the word 'important' in a strong tag to make it bold."
        template = "<p>This is very important text.</p>"
        answer = "<p>This is very <strong>important</strong> text.</p>"
        hint = "Use the strong tag around the word important."
    elif level == 5:
        title = "Links"
        theory = "The a tag creates hyperlinks. The href attribute specifies the URL. Use target='_blank' to open in a new tab."
        code = "<a href='https://example.com'>Visit Example</a>"
        challenge_type = "complete_code"
        challenge_desc = "Create a link to 'https://google.com' with the text 'Search'."
        template = "<p>Click here to </p>"
        answer = "<p>Click here to <a href='https://google.com'>Search</a></p>"
        hint = "Use the a tag with href attribute."
    elif level == 6:
        title = "Images"
        theory = "The img tag embeds images. It requires src (source) and alt (alternative text) attributes. It is a self-closing tag."
        code = "<img src='image.jpg' alt='Description'>"
        challenge_type = "complete_code"
        challenge_desc = "Add an image with src 'logo.png' and alt 'Logo' inside a div."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <img src='logo.png' alt='Logo'>\n</div>"
        hint = "Use the img tag with src and alt attributes."
    elif level == 7:
        title = "Lists"
        theory = "HTML has ordered lists (ol) with numbered items and unordered lists (ul) with bullet points. List items use li."
        code = "<ul>\n  <li>Item 1</li>\n  <li>Item 2</li>\n</ul>"
        challenge_type = "complete_code"
        challenge_desc = "Create an ordered list with two items: 'First' and 'Second'."
        template = "<ol>\n  \n  \n</ol>"
        answer = "<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>"
        hint = "Use ol for ordered list and li for each item."
    elif level == 8:
        title = "Div and Span"
        theory = "The div tag is a block-level container for grouping elements. The span tag is an inline container for text."
        code = "<div class='container'>\n  <span>Inline text</span>\n</div>"
        challenge_type = "complete_code"
        challenge_desc = "Wrap the paragraph in a div with class 'box'."
        template = "<p>Content here</p>"
        answer = "<div class='box'>\n  <p>Content here</p>\n</div>"
        hint = "Wrap the p tag with a div."
    elif level == 9:
        title = "Attributes"
        theory = "HTML elements can have attributes that provide additional information. Common attributes: id, class, style, title."
        code = "<p class='highlight' id='first' style='color:red'>Styled text</p>"
        challenge_type = "true_false"
        challenge_desc = "The id attribute must be unique within a page."
        template = ""
        answer = "true"
        hint = "Think about HTML rules for identifiers."
    elif level == 10:
        title = "Comments"
        theory = "HTML comments are not displayed in the browser. They help document code. Syntax: <!-- comment -->"
        code = "<!-- This is a comment -->\n<p>Visible content</p>"
        challenge_type = "complete_code"
        challenge_desc = "Add a comment above the paragraph saying 'Main content starts here'."
        template = "\n<p>Welcome!</p>"
        answer = "<!-- Main content starts here -->\n<p>Welcome!</p>"
        hint = "Use <!-- and --> to wrap the comment."
    elif level == 11:
        title = "Class and ID"
        theory = "Classes can be reused on multiple elements. IDs must be unique. Use . for classes and # for IDs in CSS."
        code = "<div class='box' id='main'>Content</div>"
        challenge_type = "true_false"
        challenge_desc = "You can use the same class on multiple elements."
        template = ""
        answer = "true"
        hint = "Think about the difference between class and id."
    elif level == 12:
        title = "Line Breaks"
        theory = "The br tag inserts a line break. It is a self-closing tag. Use it for poetry or addresses, not for spacing."
        code = "<p>Line 1<br>Line 2<br>Line 3</p>"
        challenge_type = "complete_code"
        challenge_desc = "Add a line break between the two sentences."
        template = "<p>First sentence. Second sentence.</p>"
        answer = "<p>First sentence.<br>Second sentence.</p>"
        hint = "Insert a br tag between the sentences."
    elif level == 13:
        title = "Horizontal Rule"
        theory = "The hr tag creates a horizontal line, used to separate content sections."
        code = "<h2>Section 1</h2>\n<p>Content</p>\n<hr>\n<h2>Section 2</h2>"
        challenge_type = "complete_code"
        challenge_desc = "Add a horizontal rule between the two paragraphs."
        template = "<p>First paragraph</p>\n\n<p>Second paragraph</p>"
        answer = "<p>First paragraph</p>\n<hr>\n<p>Second paragraph</p>"
        hint = "Use the hr tag."
    elif level == 14:
        title = "Preformatted Text"
        theory = "The pre tag displays text exactly as written, preserving spaces and line breaks. Useful for code."
        code = "<pre>\n  Line one\n  Line two\n</pre>"
        challenge_type = "predict_output"
        challenge_desc = "What text will the browser display from this pre tag?"
        template = ""
        answer = "  Line one\n  Line two"
        hint = "The pre tag preserves whitespace and line breaks exactly as written."
    elif level == 15:
        title = "HTML Entities"
        theory = "HTML entities represent special characters: &amp; for &, &lt; for <, &gt; for >, &nbsp; for space, &copy; for copyright."
        code = "<p>&copy; 2024 My Website</p>"
        challenge_type = "complete_code"
        challenge_desc = "Add the copyright entity before the year 2024."
        template = "<p> 2024 My Company</p>"
        answer = "<p>&copy; 2024 My Company</p>"
        hint = "Use the &copy; entity."
    elif level == 16:
        title = "Tables Basics"
        theory = "Tables use table, tr (row), th (header), and td (data) tags. The border attribute adds borders."
        code = "<table border='1'>\n  <tr>\n    <th>Name</th>\n    <th>Age</th>\n  </tr>\n  <tr>\n    <td>John</td>\n    <td>25</td>\n  </tr>\n</table>"
        challenge_type = "complete_code"
        challenge_desc = "Add a second row to the table with 'Jane' and '30'."
        template = "<table border='1'>\n  <tr>\n    <th>Name</th>\n    <th>Age</th>\n  </tr>\n  <tr>\n    <td>John</td>\n    <td>25</td>\n  </tr>\n  \n</table>"
        answer = "<table border='1'>\n  <tr>\n    <th>Name</th>\n    <th>Age</th>\n  </tr>\n  <tr>\n    <td>John</td>\n    <td>25</td>\n  </tr>\n  <tr>\n    <td>Jane</td>\n    <td>30</td>\n  </tr>\n</table>"
        hint = "Add another tr with two td elements."
    elif level == 17:
        title = "Table Headers"
        theory = "The th tag defines header cells in a table. Browsers usually render them bold and centered."
        code = "<table>\n  <tr>\n    <th>Product</th>\n    <th>Price</th>\n  </tr>\n</table>"
        challenge_type = "true_false"
        challenge_desc = "th elements are typically displayed in bold by default."
        template = ""
        answer = "true"
        hint = "Think about how browsers render header cells."
    elif level == 18:
        title = "Forms"
        theory = "Forms collect user input. The form tag wraps input elements. The input tag has type, name, and placeholder attributes."
        code = "<form>\n  <input type='text' name='username' placeholder='Enter name'>\n  <input type='submit' value='Send'>\n</form>"
        challenge_type = "complete_code"
        challenge_desc = "Add a text input with placeholder 'Your email' and name 'email'."
        template = "<form>\n  \n  <input type='submit' value='Submit'>\n</form>"
        answer = "<form>\n  <input type='text' name='email' placeholder='Your email'>\n  <input type='submit' value='Submit'>\n</form>"
        hint = "Use input type='text' with name and placeholder attributes."
    elif level == 19:
        title = "Input Types"
        theory = "HTML offers various input types: text, password, email, number, date, color, file, checkbox, radio, and more."
        code = "<input type='password' placeholder='Password'>\n<input type='email' placeholder='Email'>"
        challenge_type = "multiple_choice"
        challenge_desc = "Which input type hides the typed characters?"
        template = "text\npassword\nhidden\nsecret"
        answer = "password"
        hint = "Think about which input type shows dots instead of characters."
    elif level == 20:
        title = "Textarea"
        theory = "The textarea tag creates a multi-line text input. Use rows and cols attributes to set size."
        code = "<textarea rows='4' cols='50' placeholder='Write your message here...'></textarea>"
        challenge_type = "complete_code"
        challenge_desc = "Add a textarea with 3 rows and 40 columns."
        template = "<form>\n  <label>Message:</label>\n  \n</form>"
        answer = "<form>\n  <label>Message:</label>\n  <textarea rows='3' cols='40'></textarea>\n</form>"
        hint = "Use the textarea tag with rows and cols attributes."
    elif level == 21:
        title = "Select Dropdown"
        theory = "The select element creates a dropdown menu. Each option is defined by an option tag. The selected attribute preselects an option."
        code = "<select>\n  <option>Option 1</option>\n  <option selected>Option 2</option>\n</select>"
        challenge_type = "complete_code"
        challenge_desc = "Add a select dropdown with two options: 'Red' and 'Blue'."
        template = "<select>\n  \n  \n</select>"
        answer = "<select>\n  <option>Red</option>\n  <option>Blue</option>\n</select>"
        hint = "Use the select tag with option children."
    elif level == 22:
        title = "Radio Buttons"
        theory = "Radio buttons let users select one option from a group. All radio buttons in a group share the same name attribute."
        code = "<input type='radio' name='gender' value='male'> Male\n<input type='radio' name='gender' value='female'> Female"
        challenge_type = "complete_code"
        challenge_desc = "Add two radio buttons named 'color' with values 'red' and 'blue'."
        template = "<div>\n  \n  \n</div>"
        answer = "<div>\n  <input type='radio' name='color' value='red'> Red\n  <input type='radio' name='color' value='blue'> Blue\n</div>"
        hint = "Both radio inputs must have the same name attribute."
    elif level == 23:
        title = "Checkboxes"
        theory = "Checkboxes allow multiple selections. Each checkbox is independent. Use the checked attribute to pre-select."
        code = "<input type='checkbox' name='agree' checked> I agree"
        challenge_type = "complete_code"
        challenge_desc = "Add two checkboxes named 'option' with values 'a' and 'b'."
        template = "<div>\n  \n  \n</div>"
        answer = "<div>\n  <input type='checkbox' name='option' value='a'> Option A\n  <input type='checkbox' name='option' value='b'> Option B\n</div>"
        hint = "Use input type='checkbox' with name and value attributes."
    elif level == 24:
        title = "Buttons"
        theory = "The button element creates a clickable button. The type attribute can be submit, reset, or button."
        code = "<button type='button'>Click Me</button>"
        challenge_type = "complete_code"
        challenge_desc = "Add a submit button with the text 'Send Form'."
        template = "<form>\n  \n</form>"
        answer = "<form>\n  <button type='submit'>Send Form</button>\n</form>"
        hint = "Use the button tag with type='submit'."
    elif level == 25:
        title = "Fieldset and Legend"
        theory = "The fieldset tag groups related form elements. The legend tag provides a caption for the fieldset."
        code = "<fieldset>\n  <legend>Personal Info</legend>\n  <input type='text' name='name'>\n</fieldset>"
        challenge_type = "complete_code"
        challenge_desc = "Create a fieldset with legend 'Contact' and a text input named 'email'."
        template = "<form>\n  \n</form>"
        answer = "<form>\n  <fieldset>\n    <legend>Contact</legend>\n    <input type='text' name='email'>\n  </fieldset>\n</form>"
        hint = "Use fieldset to group and legend for the caption."
    elif level == 26:
        title = "Label"
        theory = "The label tag defines a label for form elements. The for attribute should match the input's id."
        code = "<label for='email'>Email:</label>\n<input type='email' id='email'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a label with text 'Name:' for an input with id 'name'."
        template = "<div>\n  \n  <input type='text' id='name'>\n</div>"
        answer = "<div>\n  <label for='name'>Name:</label>\n  <input type='text' id='name'>\n</div>"
        hint = "The for attribute on label must match the id on input."
    elif level == 27:
        title = "Required Fields"
        theory = "The required attribute makes a form field mandatory. The browser prevents submission if empty."
        code = "<input type='text' required placeholder='Required field'>"
        challenge_type = "complete_code"
        challenge_desc = "Add the required attribute to the email input."
        template = "<form>\n  <input type='email' placeholder='Enter email'>\n  <input type='submit'>\n</form>"
        answer = "<form>\n  <input type='email' required placeholder='Enter email'>\n  <input type='submit'>\n</form>"
        hint = "Add the required attribute to the input tag."
    elif level == 28:
        title = "Disabled Inputs"
        theory = "The disabled attribute makes an input unclickable and unusable. Disabled inputs are not submitted with the form."
        code = "<input type='text' disabled value='Cannot edit'>"
        challenge_type = "true_false"
        challenge_desc = "Disabled inputs are submitted with the form data."
        template = ""
        answer = "false"
        hint = "Think about whether disabled data gets sent to the server."
    elif level == 29:
        title = "Placeholder vs Value"
        theory = "The placeholder shows hint text inside the input. The value sets the actual default value. Placeholder disappears on input."
        code = "<input type='text' placeholder='Enter name' value='Default'>"
        challenge_type = "complete_code"
        challenge_desc = "Add an input with placeholder 'Your name' and default value 'John'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='text' placeholder='Your name' value='John'>\n</div>"
        hint = "Use both placeholder and value attributes."
    elif level == 30:
        title = "Min and Max Length"
        theory = "The minlength and maxlength attributes control the number of characters a user can enter."
        code = "<input type='text' minlength='3' maxlength='10'>"
        challenge_type = "complete_code"
        challenge_desc = "Add an input with minlength of 2 and maxlength of 20."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='text' minlength='2' maxlength='20'>\n</div>"
        hint = "Use minlength and maxlength attributes."
    elif level == 31:
        title = "Number Input"
        theory = "The number input type restricts input to numbers. Use min, max, and step attributes for range control."
        code = "<input type='number' min='0' max='100' step='5'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a number input with min 1, max 10, and step 1."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='number' min='1' max='10' step='1'>\n</div>"
        hint = "Use type='number' with min, max, and step attributes."
    elif level == 32:
        title = "Range Slider"
        theory = "The range input type creates a slider control. Use min, max, and step to configure the range."
        code = "<input type='range' min='0' max='100' step='10'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a range slider with min 0, max 50, and step 5."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='range' min='0' max='50' step='5'>\n</div>"
        hint = "Use type='range' with min, max, and step."
    elif level == 33:
        title = "Color Picker"
        theory = "The color input type opens a color picker. The default value is a hex color code."
        code = "<input type='color' value='#ff0000'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a color picker with default value '#00ff00' (green)."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='color' value='#00ff00'>\n</div>"
        hint = "Use type='color' with a hex value attribute."
    elif level == 34:
        title = "Date Input"
        theory = "The date input type opens a date picker. The value format is YYYY-MM-DD."
        code = "<input type='date' value='2024-01-01'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a date input with default value '2025-12-25'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='date' value='2025-12-25'>\n</div>"
        hint = "Use type='date' with a value in YYYY-MM-DD format."
    elif level == 35:
        title = "File Upload"
        theory = "The file input type lets users upload files. The accept attribute restricts file types."
        code = "<input type='file' accept='.jpg,.png'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a file input that accepts images only (.jpg, .png, .gif)."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='file' accept='.jpg,.png,.gif'>\n</div>"
        hint = "Use type='file' with an accept attribute."
    elif level == 36:
        title = "Hidden Inputs"
        theory = "The hidden input type stores data not visible to the user. It is submitted with the form."
        code = "<input type='hidden' name='user_id' value='123'>"
        challenge_type = "true_false"
        challenge_desc = "Hidden inputs are visible to the user in the browser."
        template = ""
        answer = "false"
        hint = "Think about the purpose of hidden inputs."
    elif level == 37:
        title = "URL Input"
        theory = "The url input type validates that the entered text is a valid URL. It requires http:// or https:// prefix."
        code = "<input type='url' placeholder='https://example.com'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a URL input with placeholder 'https://mysite.com'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='url' placeholder='https://mysite.com'>\n</div>"
        hint = "Use type='url' with a placeholder."
    elif level == 38:
        title = "Search Input"
        theory = "The search input type is used for search fields. It may show a clear button in some browsers."
        code = "<input type='search' placeholder='Search...'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a search input with placeholder 'Search the site...'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <input type='search' placeholder='Search the site...'>\n</div>"
        hint = "Use type='search' with a placeholder."
    elif level == 39:
        title = "Multiple Select"
        theory = "The multiple attribute on a select element allows selecting multiple options with Ctrl+click."
        code = "<select multiple>\n  <option>Item 1</option>\n  <option>Item 2</option>\n</select>"
        challenge_type = "complete_code"
        challenge_desc = "Create a select with multiple attribute and three options: A, B, C."
        template = "<select multiple>\n  \n  \n  \n</select>"
        answer = "<select multiple>\n  <option>A</option>\n  <option>B</option>\n  <option>C</option>\n</select>"
        hint = "Add the multiple attribute to the select tag."
    elif level == 40:
        title = "Datalist"
        theory = "The datalist tag provides an autocomplete list for an input. The list attribute on the input matches the datalist's id."
        code = "<input list='browsers'>\n<datalist id='browsers'>\n  <option value='Chrome'>\n  <option value='Firefox'>\n</datalist>"
        challenge_type = "complete_code"
        challenge_desc = "Create an input with a datalist containing 'Apple' and 'Banana'."
        template = "<input list='fruits'>\n<datalist id='fruits'>\n  \n  \n</datalist>"
        answer = "<input list='fruits'>\n<datalist id='fruits'>\n  <option value='Apple'>\n  <option value='Banana'>\n</datalist>"
        hint = "The input's list attribute must match the datalist's id."
    elif level == 41:
        title = "Inline Styles"
        theory = "Inline styles are applied directly to HTML elements using the style attribute. Format: property: value;"
        code = "<p style='color: blue; font-size: 20px;'>Styled text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Add a style attribute to make the text color red."
        template = "<p>Red text</p>"
        answer = "<p style='color: red;'>Red text</p>"
        hint = "Use the style attribute with 'color: red;'."
    elif level == 42:
        title = "Style Tag"
        theory = "The style tag in the head section allows defining CSS rules for the entire page."
        code = "<style>\n  p { color: blue; }\n</style>"
        challenge_type = "complete_code"
        challenge_desc = "Add a style rule that makes all h1 elements green."
        template = "<style>\n  \n</style>\n<h1>Hello</h1>"
        answer = "<style>\n  h1 { color: green; }\n</style>\n<h1>Hello</h1>"
        hint = "Use h1 as the selector and color: green as the property."
    elif level == 43:
        title = "Color Property"
        theory = "The color property sets text color. Values can be named colors (red), hex (#ff0000), rgb(), or hsl()."
        code = "<p style='color: #ff6600;'>Orange text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Make the paragraph text blue using the hex color code for blue."
        template = "<p>Blue text</p>"
        answer = "<p style='color: #0000ff;'>Blue text</p>"
        hint = "Use style='color: #0000ff;'."
    elif level == 44:
        title = "Background Color"
        theory = "The background-color property sets the background color of an element. Use the same color formats as color."
        code = "<div style='background-color: yellow;'>Highlighted</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add a background color of light blue (#add8e6) to the div."
        template = "<div>Light blue background</div>"
        answer = "<div style='background-color: #add8e6;'>Light blue background</div>"
        hint = "Use the style attribute with background-color."
    elif level == 45:
        title = "Font Size"
        theory = "The font-size property controls text size. Common units: px, em, rem, %."
        code = "<p style='font-size: 24px;'>Large text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Make the paragraph text 18 pixels using font-size."
        template = "<p>Medium text</p>"
        answer = "<p style='font-size: 18px;'>Medium text</p>"
        hint = "Use font-size: 18px in the style attribute."
    elif level == 46:
        title = "Font Family"
        theory = "The font-family property sets the font. Use fallback fonts separated by commas. Generic families: serif, sans-serif."
        code = "<p style='font-family: Arial, sans-serif;'>Arial text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Set the font to 'Georgia, serif' for the paragraph."
        template = "<p>Georgia font</p>"
        answer = "<p style='font-family: Georgia, serif;'>Georgia font</p>"
        hint = "Use font-family with the font name."
    elif level == 47:
        title = "Text Align"
        theory = "The text-align property aligns text: left, center, right, or justify."
        code = "<p style='text-align: center;'>Centered text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Center-align the paragraph text."
        template = "<p>This text should be centered</p>"
        answer = "<p style='text-align: center;'>This text should be centered</p>"
        hint = "Use text-align: center."
    elif level == 48:
        title = "Font Weight"
        theory = "The font-weight property controls boldness. Values: normal, bold, or numbers 100-900."
        code = "<p style='font-weight: bold;'>Bold text</p>"
        challenge_type = "complete_code"
        challenge_desc = "Make the paragraph text bold using font-weight."
        template = "<p>This should be bold</p>"
        answer = "<p style='font-weight: bold;'>This should be bold</p>"
        hint = "Use font-weight: bold."
    elif level == 49:
        title = "Padding"
        theory = "The padding property adds space inside an element, between the content and border. Shorthand: padding: top right bottom left."
        code = "<div style='padding: 20px;'>Padded content</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add 10 pixels of padding on all sides of the div."
        template = "<div>Content with padding</div>"
        answer = "<div style='padding: 10px;'>Content with padding</div>"
        hint = "Use padding: 10px in the style attribute."
    elif level == 50:
        title = "Margin"
        theory = "The margin property adds space outside an element, between it and other elements. Auto centers block elements."
        code = "<div style='margin: 20px;'>Content with margin</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add 15 pixels of margin on all sides of the div."
        template = "<div>Content with margin</div>"
        answer = "<div style='margin: 15px;'>Content with margin</div>"
        hint = "Use margin: 15px in the style attribute."
    elif level == 51:
        title = "Border"
        theory = "The border property adds a border. Shorthand: border: width style color. Styles: solid, dashed, dotted, etc."
        code = "<div style='border: 2px solid black;'>Bordered content</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add a 1px solid red border to the div."
        template = "<div>Content with border</div>"
        answer = "<div style='border: 1px solid red;'>Content with border</div>"
        hint = "Use border: 1px solid red."
    elif level == 52:
        title = "Width and Height"
        theory = "The width and height properties set element dimensions. Use px, %, vw, vh, or auto."
        code = "<div style='width: 200px; height: 100px;'>Fixed size</div>"
        challenge_type = "complete_code"
        challenge_desc = "Set the div to 300px wide and 150px tall."
        template = "<div>Fixed dimensions</div>"
        answer = "<div style='width: 300px; height: 150px;'>Fixed dimensions</div>"
        hint = "Use width and height properties."
    elif level == 53:
        title = "Display Property"
        theory = "The display property controls how an element is displayed. Values: block, inline, inline-block, none, flex, grid."
        code = "<span style='display: block;'>Block-level span</span>"
        challenge_type = "complete_code"
        challenge_desc = "Make the div display as inline-block."
        template = "<div>Inline-block div</div>"
        answer = "<div style='display: inline-block;'>Inline-block div</div>"
        hint = "Use display: inline-block."
    elif level == 54:
        title = "Position"
        theory = "The position property positions elements: static (default), relative, absolute, fixed, sticky."
        code = "<div style='position: relative; top: 10px; left: 20px;'>Moved element</div>"
        challenge_type = "complete_code"
        challenge_desc = "Position the div 50px from the top using relative positioning."
        template = "<div>Positioned element</div>"
        answer = "<div style='position: relative; top: 50px;'>Positioned element</div>"
        hint = "Use position: relative and top: 50px."
    elif level == 55:
        title = "Float"
        theory = "The float property pushes an element to the left or right, allowing text to wrap around it."
        code = "<img src='img.jpg' style='float: left;'>"
        challenge_type = "true_false"
        challenge_desc = "The float property can be set to left, right, or none."
        template = ""
        answer = "true"
        hint = "Think about the possible values of float."
    elif level == 56:
        title = "Overflow"
        theory = "The overflow property controls what happens when content exceeds its container. Values: visible, hidden, scroll, auto."
        code = "<div style='overflow: auto; max-height: 100px;'>Scrollable content</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add overflow: hidden to the div to clip overflowing content."
        template = "<div style='max-height: 50px;'>Content that might overflow</div>"
        answer = "<div style='overflow: hidden; max-height: 50px;'>Content that might overflow</div>"
        hint = "Use overflow: hidden."
    elif level == 57:
        title = "Opacity"
        theory = "The opacity property sets the transparency level. 0 is fully transparent, 1 is fully opaque."
        code = "<div style='opacity: 0.5;'>Semi-transparent</div>"
        challenge_type = "complete_code"
        challenge_desc = "Set the div to 75% opacity (0.75)."
        template = "<div>75% opaque</div>"
        answer = "<div style='opacity: 0.75;'>75% opaque</div>"
        hint = "Use opacity: 0.75."
    elif level == 58:
        title = "Box Shadow"
        theory = "The box-shadow property adds a shadow to an element. Syntax: offset-x offset-y blur color."
        code = "<div style='box-shadow: 5px 5px 10px gray;'>Shadowed box</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add a box-shadow that is 2px right, 2px down, 5px blur, color black."
        template = "<div>Shadowed</div>"
        answer = "<div style='box-shadow: 2px 2px 5px black;'>Shadowed</div>"
        hint = "Use box-shadow: 2px 2px 5px black."
    elif level == 59:
        title = "Border Radius"
        theory = "The border-radius property rounds the corners of an element. Use px or % for circles."
        code = "<div style='border-radius: 10px;'>Rounded corners</div>"
        challenge_type = "complete_code"
        challenge_desc = "Make the div have fully rounded corners (circle) using 50% border-radius."
        template = "<div style='width: 100px; height: 100px;'>Circle</div>"
        answer = "<div style='width: 100px; height: 100px; border-radius: 50%;'>Circle</div>"
        hint = "Use border-radius: 50%."
    elif level == 60:
        title = "CSS Selectors"
        theory = "CSS selectors target elements: element (tag), .class, #id, * (universal), descendant (space), child (>), adjacent (+)."
        code = "<style>.highlight { color: red; } #main { font-size: 20px; }</style>"
        challenge_type = "multiple_choice"
        challenge_desc = "Which CSS selector targets elements by their id?"
        template = ".class\n#id\nelement\n*"
        answer = "#id"
        hint = "The hash symbol (#) selects by id."
    elif level == 61:
        title = "Flexbox"
        theory = "Flexbox is a one-dimensional layout model. Use display: flex on the container. Main axis is set by flex-direction."
        code = "<div style='display: flex; gap: 10px;'><div>Item 1</div><div>Item 2</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Make the container a flexbox with display: flex."
        template = "<div style='display: flex;'><div>Item 1</div><div>Item 2</div></div>"
        answer = "<div style='display: flex;'><div>Item 1</div><div>Item 2</div></div>"
        hint = "The container already has display: flex. Add gap: 10px."
    elif level == 62:
        title = "Flex Direction"
        theory = "flex-direction sets the main axis: row (default), column, row-reverse, column-reverse."
        code = "<div style='display: flex; flex-direction: column;'><div>Top</div><div>Bottom</div></div>"
        challenge_type = "predict_output"
        challenge_desc = "With flex-direction: column, how will flex items be arranged?"
        template = ""
        answer = "Vertically from top to bottom"
        hint = "Column direction stacks items vertically."
    elif level == 63:
        title = "Justify Content"
        theory = "justify-content aligns items along the main axis. Values: flex-start, center, flex-end, space-between, space-around."
        code = "<div style='display: flex; justify-content: center;'><div>Center</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Center the flex items horizontally using justify-content."
        template = "<div style='display: flex;'><div>Item 1</div><div>Item 2</div></div>"
        answer = "<div style='display: flex; justify-content: center;'><div>Item 1</div><div>Item 2</div></div>"
        hint = "Use justify-content: center."
    elif level == 64:
        title = "Align Items"
        theory = "align-items aligns items along the cross axis. Values: stretch, center, flex-start, flex-end, baseline."
        code = "<div style='display: flex; align-items: center; height: 100px;'><div>Centered</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Vertically center the items using align-items."
        template = "<div style='display: flex; height: 100px;'><div>Item</div></div>"
        answer = "<div style='display: flex; align-items: center; height: 100px;'><div>Item</div></div>"
        hint = "Use align-items: center."
    elif level == 65:
        title = "Flex Wrap"
        theory = "flex-wrap controls whether items wrap to a new line. Values: nowrap, wrap, wrap-reverse."
        code = "<div style='display: flex; flex-wrap: wrap;'><div>Item</div><div>Item</div></div>"
        challenge_type = "true_false"
        challenge_desc = "flex-wrap: nowrap allows items to wrap to the next line."
        template = ""
        answer = "false"
        hint = "nowrap keeps items on one line."
    elif level == 66:
        title = "Gap"
        theory = "The gap property sets spacing between flex or grid items. Works in both axes."
        code = "<div style='display: flex; gap: 20px;'><div>Item</div><div>Item</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Add a 15px gap between flex items."
        template = "<div style='display: flex;'><div>Item 1</div><div>Item 2</div></div>"
        answer = "<div style='display: flex; gap: 15px;'><div>Item 1</div><div>Item 2</div></div>"
        hint = "Use gap: 15px."
    elif level == 67:
        title = "CSS Grid"
        theory = "CSS Grid is a two-dimensional layout. Use display: grid. Define columns with grid-template-columns."
        code = "<div style='display: grid; grid-template-columns: 1fr 1fr; gap: 10px;'><div>Left</div><div>Right</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Create a grid with two equal columns using grid-template-columns."
        template = "<div style='display: grid;'><div>Col 1</div><div>Col 2</div></div>"
        answer = "<div style='display: grid; grid-template-columns: 1fr 1fr;'><div>Col 1</div><div>Col 2</div></div>"
        hint = "Use grid-template-columns: 1fr 1fr."
    elif level == 68:
        title = "Grid Columns"
        theory = "grid-template-columns defines the number and size of columns. Use px, fr, %, auto, repeat()."
        code = "<div style='display: grid; grid-template-columns: repeat(3, 1fr);'><div>1</div><div>2</div><div>3</div></div>"
        challenge_type = "complete_code"
        challenge_desc = "Create a 3-column grid using repeat(3, 1fr)."
        template = "<div style='display: grid;'><div>A</div><div>B</div><div>C</div></div>"
        answer = "<div style='display: grid; grid-template-columns: repeat(3, 1fr);'><div>A</div><div>B</div><div>C</div></div>"
        hint = "Use grid-template-columns: repeat(3, 1fr)."
    elif level == 69:
        title = "Media Queries"
        theory = "Media queries apply styles based on device characteristics like screen width. Syntax: @media (max-width: 768px) { }"
        code = "<style>@media (max-width: 600px) { body { font-size: 14px; } }</style>"
        challenge_type = "complete_code"
        challenge_desc = "Add a media query that changes the body font-size to 12px when the screen is narrower than 480px."
        template = "<style>\n  \n</style>"
        answer = "<style>\n  @media (max-width: 480px) { body { font-size: 12px; } }\n</style>"
        hint = "Use @media (max-width: 480px) as the breakpoint."
    elif level == 70:
        title = "Responsive Design"
        theory = "Responsive design uses flexible layouts, media queries, and relative units to work on all screen sizes."
        code = "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        challenge_type = "true_false"
        challenge_desc = "The viewport meta tag is essential for responsive design on mobile."
        template = ""
        answer = "true"
        hint = "Think about how mobile browsers handle page scaling."
    elif level == 71:
        title = "CSS Variables"
        theory = "CSS custom properties (variables) store reusable values. Define with --name, use with var(--name)."
        code = "<style>:root { --main-color: blue; } h1 { color: var(--main-color); }</style>"
        challenge_type = "complete_code"
        challenge_desc = "Create a CSS variable --primary set to red, and use it on the h1."
        template = "<style>\n  \n</style>\n<h1>Red heading</h1>"
        answer = "<style>\n  :root { --primary: red; }\n  h1 { color: var(--primary); }\n</style>\n<h1>Red heading</h1>"
        hint = "Define the variable in :root and use it with var()."
    elif level == 72:
        title = "Pseudo Classes"
        theory = "Pseudo-classes style elements in a specific state: :hover, :focus, :active, :nth-child(), :first-child."
        code = "<style>a:hover { color: red; }</style>"
        challenge_type = "complete_code"
        challenge_desc = "Make the button turn blue when hovered using the :hover pseudo-class."
        template = "<style>\n  \n</style>\n<button>Hover me</button>"
        answer = "<style>\n  button:hover { color: blue; }\n</style>\n<button>Hover me</button>"
        hint = "Use button:hover as the selector."
    elif level == 73:
        title = "Transitions"
        theory = "The transition property creates smooth animations between states. Syntax: transition: property duration timing-function."
        code = "<style>div { transition: all 0.3s ease; } div:hover { transform: scale(1.1); }</style>"
        challenge_type = "complete_code"
        challenge_desc = "Add a 0.5 second transition on the color property."
        template = "<style>\n  div { color: black; }\n  div:hover { color: red; }\n</style>\n<div>Hover</div>"
        answer = "<style>\n  div { color: black; transition: color 0.5s; }\n  div:hover { color: red; }\n</style>\n<div>Hover</div>"
        hint = "Add transition: color 0.5s to the div."
    elif level == 74:
        title = "Transform"
        theory = "The transform property modifies element appearance: translate(), scale(), rotate(), skew()."
        code = "<div style='transform: rotate(45deg);'>Rotated</div>"
        challenge_type = "complete_code"
        challenge_desc = "Scale the div to 1.5 times its size using transform: scale(1.5)."
        template = "<div>Scaled</div>"
        answer = "<div style='transform: scale(1.5);'>Scaled</div>"
        hint = "Use transform: scale(1.5)."
    elif level == 75:
        title = "Keyframes"
        theory = "Keyframes define animation sequences. Use @keyframes name { from { } to { } } or percentage steps."
        code = "<style>@keyframes slide { from { transform: translateX(0); } to { transform: translateX(100px); } } div { animation: slide 2s; }</style>"
        challenge_type = "complete_code"
        challenge_desc = "Create a keyframe animation named 'fade' that goes from opacity 0 to opacity 1."
        template = "<style>\n  @keyframes fade {\n    from { opacity: 0; }\n    to { opacity: 1; }\n  }\n  div { animation: fade 2s; }\n</style>\n<div>Fading in</div>"
        answer = "<style>\n  @keyframes fade {\n    from { opacity: 0; }\n    to { opacity: 1; }\n  }\n  div { animation: fade 2s; }\n</style>\n<div>Fading in</div>"
        hint = "The answer is already in the template. Submit it as-is."
    elif level == 76:
        title = "Z-Index"
        theory = "The z-index property controls the stacking order of positioned elements. Higher values appear on top."
        code = "<div style='position: relative; z-index: 10;'>On top</div>"
        challenge_type = "true_false"
        challenge_desc = "z-index only works on positioned elements (position not static)."
        template = ""
        answer = "true"
        hint = "Think about which elements can use z-index."
    elif level == 77:
        title = "Box Sizing"
        theory = "box-sizing: border-box includes padding and border in the element's total width. Content-box (default) adds them on top."
        code = "<div style='box-sizing: border-box; width: 100px; padding: 10px;'>100px total</div>"
        challenge_type = "complete_code"
        challenge_desc = "Set box-sizing to border-box on the div."
        template = "<div style='width: 200px; padding: 20px;'>200px including padding</div>"
        answer = "<div style='box-sizing: border-box; width: 200px; padding: 20px;'>200px including padding</div>"
        hint = "Use box-sizing: border-box."
    elif level == 78:
        title = "Visibility"
        theory = "The visibility property hides elements but keeps their space. Values: visible, hidden. Use display: none to remove space."
        code = "<div style='visibility: hidden;'>Hidden but takes space</div>"
        challenge_type = "true_false"
        challenge_desc = "visibility: hidden removes the element from the layout flow."
        template = ""
        answer = "false"
        hint = "Compare visibility: hidden with display: none."
    elif level == 79:
        title = "Min and Max Width"
        theory = "min-width and max-width constrain an element's width. Useful for responsive layouts."
        code = "<div style='min-width: 200px; max-width: 800px;'>Responsive width</div>"
        challenge_type = "complete_code"
        challenge_desc = "Set min-width to 100px and max-width to 500px on the div."
        template = "<div>Responsive</div>"
        answer = "<div style='min-width: 100px; max-width: 500px;'>Responsive</div>"
        hint = "Use min-width and max-width properties."
    elif level == 80:
        title = "Object Fit"
        theory = "The object-fit property controls how an image or video fits in its container. Values: cover, contain, fill, scale-down."
        code = "<img src='photo.jpg' style='width: 200px; height: 200px; object-fit: cover;'>"
        challenge_type = "multiple_choice"
        challenge_desc = "Which object-fit value crops the image to fill the container while maintaining aspect ratio?"
        template = "cover\ncontain\nfill\nscale-down"
        answer = "cover"
        hint = "Cover fills the container and crops the excess."
    elif level == 81:
        title = "Semantic HTML"
        theory = "Semantic HTML uses meaningful tags: header, nav, main, article, section, aside, footer. Improves accessibility and SEO."
        code = "<header>Site Header</header>\n<main>\n  <article>Content</article>\n</main>\n<footer>Footer</footer>"
        challenge_type = "complete_code"
        challenge_desc = "Create a semantic layout with header, main, and footer tags."
        template = "<body>\n  \n  \n  \n</body>"
        answer = "<body>\n  <header>Header</header>\n  <main>Main content</main>\n  <footer>Footer</footer>\n</body>"
        hint = "Use header, main, and footer tags."
    elif level == 82:
        title = "Accessibility"
        theory = "Web accessibility (a11y) ensures websites work for people with disabilities. Use alt text, ARIA labels, semantic HTML."
        code = "<img src='logo.png' alt='Company Logo'>\n<button aria-label='Close'>X</button>"
        challenge_type = "true_false"
        challenge_desc = "The alt attribute on images is important for screen reader users."
        template = ""
        answer = "true"
        hint = "Think about how blind users access web content."
    elif level == 83:
        title = "SEO Meta Tags"
        theory = "Meta tags provide metadata to search engines: description, keywords, author, robots. The title tag is crucial for SEO."
        code = "<head>\n  <meta name='description' content='Free coding tutorials'>\n  <meta name='keywords' content='HTML, CSS, coding'>\n  <title>Learn to Code</title>\n</head>"
        challenge_type = "complete_code"
        challenge_desc = "Add a meta description tag with content 'Learn HTML basics'."
        template = "<head>\n  <title>My Page</title>\n  \n</head>"
        answer = "<head>\n  <title>My Page</title>\n  <meta name='description' content='Learn HTML basics'>\n</head>"
        hint = "Use meta name='description' with content attribute."
    elif level == 84:
        title = "Canvas"
        theory = "The canvas element draws graphics using JavaScript. It requires an id, width, and height."
        code = "<canvas id='myCanvas' width='400' height='200'></canvas>"
        challenge_type = "complete_code"
        challenge_desc = "Add a canvas element with id 'draw', width 300, height 200."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <canvas id='draw' width='300' height='200'></canvas>\n</div>"
        hint = "Use the canvas tag with id, width, and height attributes."
    elif level == 85:
        title = "SVG"
        theory = "SVG (Scalable Vector Graphics) defines vector graphics in XML. Shapes: circle, rect, path, polygon."
        code = "<svg width='100' height='100'>\n  <circle cx='50' cy='50' r='40' fill='blue' />\n</svg>"
        challenge_type = "complete_code"
        challenge_desc = "Add an SVG with a red circle at center (50,50) with radius 30."
        template = "<svg width='100' height='100'>\n  \n</svg>"
        answer = "<svg width='100' height='100'>\n  <circle cx='50' cy='50' r='30' fill='red' />\n</svg>"
        hint = "Use the circle tag with cx, cy, r, and fill attributes."
    elif level == 86:
        title = "Audio"
        theory = "The audio element embeds sound files. The controls attribute shows playback controls. Use source tags for formats."
        code = "<audio controls>\n  <source src='song.mp3' type='audio/mpeg'>\n</audio>"
        challenge_type = "complete_code"
        challenge_desc = "Add an audio element with controls and a source file 'music.mp3'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <audio controls>\n    <source src='music.mp3' type='audio/mpeg'>\n  </audio>\n</div>"
        hint = "Use the audio tag with controls attribute."
    elif level == 87:
        title = "Video"
        theory = "The video element embeds video files. Use controls, width, height, and source tags for different formats."
        code = "<video width='320' height='240' controls>\n  <source src='video.mp4' type='video/mp4'>\n</video>"
        challenge_type = "complete_code"
        challenge_desc = "Add a video element with width 400, controls, and source 'movie.mp4'."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <video width='400' controls>\n    <source src='movie.mp4' type='video/mp4'>\n  </video>\n</div>"
        hint = "Use the video tag with width, controls, and source."
    elif level == 88:
        title = "Iframes"
        theory = "The iframe tag embeds another HTML page. Use src, width, height, and allow for permissions."
        code = "<iframe src='https://example.com' width='600' height='400'></iframe>"
        challenge_type = "complete_code"
        challenge_desc = "Add an iframe with src 'https://example.com' and width 500, height 300."
        template = "<div>\n  \n</div>"
        answer = "<div>\n  <iframe src='https://example.com' width='500' height='300'></iframe>\n</div>"
        hint = "Use the iframe tag with src, width, and height."
    elif level == 89:
        title = "Local Storage"
        theory = "localStorage stores data in the browser with no expiration. Use setItem(), getItem(), removeItem()."
        code = "<script>localStorage.setItem('key', 'value'); console.log(localStorage.getItem('key'));</script>"
        challenge_type = "true_false"
        challenge_desc = "localStorage data persists after the browser is closed and reopened."
        template = ""
        answer = "true"
        hint = "Think about the difference between localStorage and sessionStorage."
    elif level == 90:
        title = "Session Storage"
        theory = "sessionStorage stores data for the current session only. Data is cleared when the tab is closed."
        code = "<script>sessionStorage.setItem('temp', 'data');</script>"
        challenge_type = "true_false"
        challenge_desc = "sessionStorage data persists after the browser is closed."
        template = ""
        answer = "false"
        hint = "Session storage is cleared when the tab closes."
    elif level == 91:
        title = "Drag and Drop"
        theory = "HTML drag-and-drop API uses draggable attribute, dragstart, dragover, and drop events."
        code = "<div draggable='true' ondragstart='event.dataTransfer.setData(\"text\", this.id)'>Drag me</div>"
        challenge_type = "complete_code"
        challenge_desc = "Make the div draggable by adding the draggable attribute."
        template = "<div>Drag me</div>"
        answer = "<div draggable='true'>Drag me</div>"
        hint = "Add draggable='true' to the div."
    elif level == 92:
        title = "Geolocation"
        theory = "The Geolocation API gets the user's position. Use navigator.geolocation.getCurrentPosition()."
        code = "<script>navigator.geolocation.getCurrentPosition(pos => { console.log(pos.coords.latitude); });</script>"
        challenge_type = "true_false"
        challenge_desc = "The Geolocation API requires user permission before accessing location."
        template = ""
        answer = "true"
        hint = "Think about privacy requirements for location data."
    elif level == 93:
        title = "Microdata"
        theory = "Microdata adds structured data to HTML using itemscope, itemtype, and itemprop attributes for search engines."
        code = "<div itemscope itemtype='https://schema.org/Person'>\n  <span itemprop='name'>John Doe</span>\n</div>"
        challenge_type = "complete_code"
        challenge_desc = "Add itemscope and itemtype='https://schema.org/Product' to the div."
        template = "<div>\n  <span>Product Name</span>\n</div>"
        answer = "<div itemscope itemtype='https://schema.org/Product'>\n  <span>Product Name</span>\n</div>"
        hint = "Add itemscope and itemtype attributes to the div."
    elif level == 94:
        title = "Open Graph"
        theory = "Open Graph meta tags control how content appears when shared on social media (og:title, og:description, og:image)."
        code = "<meta property='og:title' content='My Page'>\n<meta property='og:description' content='Description'>"
        challenge_type = "complete_code"
        challenge_desc = "Add an Open Graph title meta tag with property='og:title' and content='My Site'."
        template = "<head>\n  \n</head>"
        answer = "<head>\n  <meta property='og:title' content='My Site'>\n</head>"
        hint = "Use meta with property='og:title' and content attributes."
    elif level == 95:
        title = "Twitter Cards"
        theory = "Twitter Card meta tags control how content appears on Twitter. Types: summary, summary_large_image, app, player."
        code = "<meta name='twitter:card' content='summary'>\n<meta name='twitter:title' content='My Page'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a Twitter card meta tag with name='twitter:card' and content='summary'."
        template = "<head>\n  \n</head>"
        answer = "<head>\n  <meta name='twitter:card' content='summary'>\n</head>"
        hint = "Use meta with name='twitter:card'."
    elif level == 96:
        title = "Progressive Web Apps"
        theory = "PWAs are web apps that can be installed on devices. Require a manifest.json and service worker for offline support."
        code = "<link rel='manifest' href='/manifest.json'>\n<meta name='theme-color' content='#0400FF'>"
        challenge_type = "complete_code"
        challenge_desc = "Add a manifest link tag with rel='manifest' and href='/app.webmanifest'."
        template = "<head>\n  \n</head>"
        answer = "<head>\n  <link rel='manifest' href='/app.webmanifest'>\n</head>"
        hint = "Use link rel='manifest' with href attribute."
    elif level == 97:
        title = "Service Workers"
        theory = "Service workers are scripts that run in the background, enabling offline support, push notifications, and caching."
        code = "<script>navigator.serviceWorker.register('/sw.js');</script>"
        challenge_type = "true_false"
        challenge_desc = "Service workers can intercept network requests and cache resources."
        template = ""
        answer = "true"
        hint = "Think about the main purpose of service workers."
    elif level == 98:
        title = "Web Workers"
        theory = "Web Workers run JavaScript in a background thread, preventing UI blocking. Communicate via postMessage()."
        code = "<script>const worker = new Worker('worker.js'); worker.postMessage('start');</script>"
        challenge_type = "true_false"
        challenge_desc = "Web Workers have access to the DOM."
        template = ""
        answer = "false"
        hint = "Think about what workers can and cannot access."
    elif level == 99:
        title = "Server-Sent Events"
        theory = "SSE (Server-Sent Events) allows the server to push updates to the client over HTTP. Use EventSource API."
        code = "<script>const source = new EventSource('/events'); source.onmessage = e => console.log(e.data);</script>"
        challenge_type = "complete_code"
        challenge_desc = "Create an EventSource listening to '/updates'."
        template = "<script>\n  \n</script>"
        answer = "<script>\n  const source = new EventSource('/updates');\n</script>"
        hint = "Use new EventSource('/updates')."
    elif level == 100:
        title = "HTML Final Project"
        theory = "You have mastered HTML! Combine everything: semantic structure, forms, CSS styling, responsive design, and accessibility."
        code = "<!DOCTYPE html>\n<html lang='en'>\n<head>\n  <meta charset='UTF-8'>\n  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n  <title>My Portfolio</title>\n  <style>\n    body { font-family: Arial; margin: 0; padding: 20px; }\n    .container { max-width: 800px; margin: 0 auto; }\n  </style>\n</head>\n<body>\n  <div class='container'>\n    <h1>Welcome</h1>\n    <p>Final project complete!</p>\n  </div>\n</body>\n</html>"
        challenge_type = "complete_code"
        challenge_desc = "Create a complete HTML page with a title 'My Portfolio' and a body with 'Hello World'."
        template = "<!DOCTYPE html>\n<html>\n<head>\n  <title>My Portfolio</title>\n</head>\n<body>\n  \n</body>\n</html>"
        answer = "<!DOCTYPE html>\n<html>\n<head>\n  <title>My Portfolio</title>\n</head>\n<body>\n  <p>Hello World</p>\n</body>\n</html>"
        hint = "Add a p tag with Hello World inside the body."

    LESSON_TEMPLATES.append({
        "language": "html",
        "level_number": level,
        "title": title,
        "theory_text": theory,
        "code_example": code,
        "challenge_type": challenge_type,
        "challenge_description": challenge_desc,
        "challenge_template": template,
        "correct_answer": answer,
        "hint": hint,
        "xp_reward": xp,
        "difficulty": difficulty
    })

def generate_sql():
    sql_lines = []
    sql_lines.append("-- HTML lessons seed data (100 levels)")
    sql_lines.append("")

    for lesson in LESSON_TEMPLATES:
        lang = lesson["language"].replace("'", "''")
        title = lesson["title"].replace("'", "''")
        theory = lesson["theory_text"].replace("'", "''")
        code = lesson["code_example"].replace("'", "''")
        ctype = lesson["challenge_type"]
        cdesc = lesson["challenge_description"].replace("'", "''")
        template = lesson["challenge_template"].replace("'", "''")
        answer = lesson["correct_answer"].replace("'", "''")
        hint = lesson["hint"].replace("'", "''")
        xp = lesson["xp_reward"]
        diff = lesson["difficulty"]
        num = lesson["level_number"]

        sql = "INSERT INTO lessons (language, level_number, title, theory_text, code_example, challenge_type, challenge_description, challenge_template, correct_answer, hint, xp_reward, difficulty, is_active) VALUES ('" + lang + "', " + str(num) + ", '" + title + "', '" + theory + "', '" + code + "', '" + ctype + "', '" + cdesc + "', '" + template + "', '" + answer + "', '" + hint + "', " + str(xp) + ", '" + diff + "', 1);"
        sql_lines.append(sql)

    return "\n".join(sql_lines)

if __name__ == "__main__":
    sql = generate_sql()
    with open("seed_html_lessons.sql", "w") as f:
        f.write(sql)
    print("Generated " + str(len(LESSON_TEMPLATES)) + " HTML lesson SQL statements")
    print("Output written to seed_html_lessons.sql")